insert into calles (nombre) values ('1 DE ENERO');
insert into calles (nombre) values ('15 DE FEBRERO');
insert into calles (nombre) values ('3 DE JULIO');
insert into calles (nombre) values ('5 DE OCTUBRE');
insert into calles (nombre) values ('ABEL FLEURY');
insert into calles (nombre) values ('ACHEN (PIEDRA POROSA)');
insert into calles (nombre) values ('ADA MARIA ELFLEIN');
insert into calles (nombre) values ('ADOLFO ALSINA');
insert into calles (nombre) values ('ADOLFO FOUROUS');
insert into calles (nombre) values ('AEROPUERTO BARILOCHE');
insert into calles (nombre) values ('AGACHONA DE COLLAR');
insert into calles (nombre) values ('AGUADA DE GUERRA');
insert into calles (nombre) values ('AGUAS AZULES');
insert into calles (nombre) values ('AGUILA');
insert into calles (nombre) values ('AGUILUCHO ANDINO');
insert into calles (nombre) values ('AIME PAINE');
insert into calles (nombre) values ('ALANIZ');
insert into calles (nombre) values ('ALBATROS');
insert into calles (nombre) values ('ALBERTO LAGOS');
insert into calles (nombre) values ('ALBERTO WILLIAMS');
insert into calles (nombre) values ('ALEJANDRO LELOIR');
insert into calles (nombre) values ('ALELIES');
insert into calles (nombre) values ('ALEMANIA');
insert into calles (nombre) values ('ALFONSINA STORNI');
insert into calles (nombre) values ('ALFREDO BIGATTI');
insert into calles (nombre) values ('ALFREDO GUTTERO');
insert into calles (nombre) values ('ALGARROBO');
insert into calles (nombre) values ('ALICIA MOREAU DE JUSTO');
insert into calles (nombre) values ('ALICURA');
insert into calles (nombre) values ('ALIOLA');
insert into calles (nombre) values ('ALMAFUERTE');
insert into calles (nombre) values ('ALMIRANTE GUILLERMO BROWN');
insert into calles (nombre) values ('ALTUE');
insert into calles (nombre) values ('ALVARO YUNQUE');
insert into calles (nombre) values ('AMANCAY');
insert into calles (nombre) values ('AMANCAY, DINA HUAPI');
insert into calles (nombre) values ('AMAPOLAS');
insert into calles (nombre) values ('AMERICO GUGLIELMETTI');
insert into calles (nombre) values ('AMERICO PANOZZI');
insert into calles (nombre) values ('ANDRES CHAZARRETA');
insert into calles (nombre) values ('ANEMONAS');
insert into calles (nombre) values ('ANGEL DELLA VALLE');
insert into calles (nombre) values ('ANGEL LAVAGNINO');
insert into calles (nombre) values ('ANGELICA ACEVEDO');
insert into calles (nombre) values ('ANTARES');
insert into calles (nombre) values ('ANTARTIDA ARGENTINA');
insert into calles (nombre) values ('ANTONIO BERNI');
insert into calles (nombre) values ('ANTONIO BERUTI');
insert into calles (nombre) values ('ANTONIO TARRAGO ROS (P)');
insert into calles (nombre) values ('ANTONIO VIVALDI');
insert into calles (nombre) values ('ANTONIO ZANDEGIACOMO');
insert into calles (nombre) values ('ANTU');
insert into calles (nombre) values ('ANTU - CO');
insert into calles (nombre) values ('APARTADOS');
insert into calles (nombre) values ('ARCHIPIELAGO DEL SUR EX CORAL');
insert into calles (nombre) values ('ARELAUQUEN');
insert into calles (nombre) values ('ARGENTINA (DINA HUAPI)');
insert into calles (nombre) values ('ARGO');
insert into calles (nombre) values ('ARIES');
insert into calles (nombre) values ('ARJONA');
insert into calles (nombre) values ('ARMANDO LAROCHETTE');
insert into calles (nombre) values ('ARMANDO TEJADA GOMEZ');
insert into calles (nombre) values ('ARRAYANES');
insert into calles (nombre) values ('ARRAYANES-MELIPAL');
insert into calles (nombre) values ('ARROYO CASCADA');
insert into calles (nombre) values ('ARROYO CASTILLA');
insert into calles (nombre) values ('ARROYO DE LA CHINA');
insert into calles (nombre) values ('ARROYO DEL MEDIO');
insert into calles (nombre) values ('ARROYO ESCALERA');
insert into calles (nombre) values ('ARROYO FRESCO');
insert into calles (nombre) values ('ARROYO LAS PIEDRITAS');
insert into calles (nombre) values ('ARROYO RUCACO');
insert into calles (nombre) values ('ARROYO TORRONTEGUI');
insert into calles (nombre) values ('ARROYO TUQUECO');
insert into calles (nombre) values ('ARROYO VAN TITTER');
insert into calles (nombre) values ('ARTURO JAURETCHE');
insert into calles (nombre) values ('ASTOR PIAZOLLA');
insert into calles (nombre) values ('ASUNCION');
insert into calles (nombre) values ('ATAHUALPA YUPANQUI');
insert into calles (nombre) values ('AUGUSTE RENOIR');
insert into calles (nombre) values ('AUGUSTO BALLERINI');
insert into calles (nombre) values ('AUSTRIA');
insert into calles (nombre) values ('AVENIDA BENITO BOOCK');
insert into calles (nombre) values ('AVENIDA BRIGADIER JUAN MANUEL DE ROSAS');
insert into calles (nombre) values ('AVENIDA CACIQUE SAIHUEQUE');
insert into calles (nombre) values ('AVENIDA CARLOS MANUEL BUSTOS');
insert into calles (nombre) values ('AVENIDA CARLOS WIEDERHOLD');
insert into calles (nombre) values ('AVENIDA CERRO CAPILLA');
insert into calles (nombre) values ('AVENIDA CERRO CATEDRAL');
insert into calles (nombre) values ('AVENIDA CERRO DE LA VENTANA');
insert into calles (nombre) values ('AVENIDA CERRO LOS CANTAROS');
insert into calles (nombre) values ('AVENIDA CERRO TRONADOR');
insert into calles (nombre) values ('AVENIDA CORE CORE');
insert into calles (nombre) values ('AVENIDA DE LA VIRREINA');
insert into calles (nombre) values ('AVENIDA DE LAS VICTORIAS');
insert into calles (nombre) values ('AVENIDA DE LOS AMANCAY');
insert into calles (nombre) values ('AVENIDA DE LOS ESCRITORES ARGENTINOS');
insert into calles (nombre) values ('AVENIDA DE LOS PIONEROS');
insert into calles (nombre) values ('AVENIDA DEL CAMPANARIO');
insert into calles (nombre) values ('AVENIDA DEL CENTENARIO');
insert into calles (nombre) values ('AVENIDA DEL ESTE');
insert into calles (nombre) values ('AVENIDA DEL LAGO');
insert into calles (nombre) values ('AVENIDA DEL VADO (DINA HUAPI)');
insert into calles (nombre) values ('AVENIDA DOCE DE OCTUBRE');
insert into calles (nombre) values ('AVENIDA DON ORIONE');
insert into calles (nombre) values ('AVENIDA EXEQUIEL BUSTILLO KM.');
insert into calles (nombre) values ('AVENIDA HUEMUL (DINA HUAPI)');
insert into calles (nombre) values ('AVENIDA JARDIN BOTANICO');
insert into calles (nombre) values ('AVENIDA JOSE DE SAN MARTIN');
insert into calles (nombre) values ('AVENIDA LAS ARDILLAS');
insert into calles (nombre) values ('AVENIDA MANUEL BELGRANO');
insert into calles (nombre) values ('AVENIDA PATAGONIA');
insert into calles (nombre) values ('AVENIDA RIO NEGRO');
insert into calles (nombre) values ('AVENIDA TRES LAGOS');
insert into calles (nombre) values ('AVUTARDAS');
insert into calles (nombre) values ('AYAYEMA');
insert into calles (nombre) values ('AYELEN (ALEGRIA)');
insert into calles (nombre) values ('AYOHUMA');
insert into calles (nombre) values ('AZALEA');
insert into calles (nombre) values ('BACH');
insert into calles (nombre) values ('BACH- (LLAO-LLAO)');
insert into calles (nombre) values ('BAJADA CHALLHUACO');
insert into calles (nombre) values ('BAJADA DE LOS BOSQUES NATIVOS');
insert into calles (nombre) values ('BAJADA DE LOS MAITENES- BRIO.LOS MAITENE');
insert into calles (nombre) values ('BAJADA DE SELVA NEGRA');
insert into calles (nombre) values ('BAJADA DEL CERRO - VILLA LLANQUIHUE -');
insert into calles (nombre) values ('BAJADA DEL ESPERANTO');
insert into calles (nombre) values ('BAJADA DEL PARANA');
insert into calles (nombre) values ('BAJADA DEL SOL');
insert into calles (nombre) values ('BAJADA DEL WOODVILLE');
insert into calles (nombre) values ('BAJADA Nº 1 TRUCHA ARCO IRIS');
insert into calles (nombre) values ('BAJADA Nº 10 TRUCHA DEL LAGO');
insert into calles (nombre) values ('BAJADA Nº 11 SALMON DEL PACIFICO');
insert into calles (nombre) values ('BAJADA Nº 2 TRUCHA MARRON');
insert into calles (nombre) values ('BAJADA Nº 3 TRUCHA FONTINALIS');
insert into calles (nombre) values ('BAJADA Nº 4 PEJERREY PATAGONICO');
insert into calles (nombre) values ('BAJADA Nº 5 TRUCHA PERCA');
insert into calles (nombre) values ('BAJADA Nº 6 TRUCHA PULLEN');
insert into calles (nombre) values ('BAJADA Nº 7 TRUCHA PELADILLA');
insert into calles (nombre) values ('BAJADA Nº 8 TRUCHA CARPA');
insert into calles (nombre) values ('BAJADA Nº 9 SALMON DEL TRAFUL');
insert into calles (nombre) values ('BANDURRIAS');
insert into calles (nombre) values ('BARTOLOME MITRE');
insert into calles (nombre) values ('BASE CERRO CATEDRAL');
insert into calles (nombre) values ('BASILEA');
insert into calles (nombre) values ('BATALLA DE BACACAY');
insert into calles (nombre) values ('BATALLA DE CAMACUA');
insert into calles (nombre) values ('BATALLA DE CARABOBO');
insert into calles (nombre) values ('BATALLA DE ITUZAINGO');
insert into calles (nombre) values ('BATALLA DE MAIPU');
insert into calles (nombre) values ('BECASINAS');
insert into calles (nombre) values ('BEETHOVEN');
insert into calles (nombre) values ('BELGRANO - MELIPAL');
insert into calles (nombre) values ('BELISARIO ROLDAN');
insert into calles (nombre) values ('BENITO CRESPO');
insert into calles (nombre) values ('BENITO QUINQUELA MARTIN');
insert into calles (nombre) values ('BENITO VEREERTBRUGHEN');
insert into calles (nombre) values ('BERNARDINO RIVADAVIA');
insert into calles (nombre) values ('BERNARDO GLAS');
insert into calles (nombre) values ('BERNARDO HOUSSAY');
insert into calles (nombre) values ('BERNARDO MANE');
insert into calles (nombre) values ('BERNARDO OHIGGINS');
insert into calles (nombre) values ('BIGUAES');
insert into calles (nombre) values ('BIRDIE');
insert into calles (nombre) values ('BOGOTA');
insert into calles (nombre) values ('BOOCK L. F. DE - MELIPAL');
insert into calles (nombre) values ('BORIS FURMAN');
insert into calles (nombre) values ('BOSQUE LINDO');
insert into calles (nombre) values ('BOSQUECITOS');
insert into calles (nombre) values ('BOYACA');
insert into calles (nombre) values ('BRAHMS');
insert into calles (nombre) values ('BRASIL, DINA HUAPI');
insert into calles (nombre) values ('BRASILIA');
insert into calles (nombre) values ('BRAZO BLEST');
insert into calles (nombre) values ('BRAZO CAMPANARIO');
insert into calles (nombre) values ('BRAZO HUEMUL');
insert into calles (nombre) values ('BRAZO MACHETE');
insert into calles (nombre) values ('BRAZO TRISTEZA');
insert into calles (nombre) values ('BRIO 2 AGOSTO *GASTR. CASA');
insert into calles (nombre) values ('BRIO 40 VIVIENDAS');
insert into calles (nombre) values ('BRIO PEUMAYEN');
insert into calles (nombre) values ('BRIO. 106 - CASA');
insert into calles (nombre) values ('BRIO. 112 VIV CASA');
insert into calles (nombre) values ('BRIO. 120 VIV.');
insert into calles (nombre) values ('BRIO. 121 VIV CASA');
insert into calles (nombre) values ('BRIO. 130 VIV. CASA');
insert into calles (nombre) values ('BRIO. 134 VIV. CASA');
insert into calles (nombre) values ('BRIO. 136 VIV. CASA');
insert into calles (nombre) values ('BRIO. 144 VIV. CASA');
insert into calles (nombre) values ('BRIO. 144 VIV. EDIF');
insert into calles (nombre) values ('BRIO. 150 VIV (CALFU RUCA ) CASA');
insert into calles (nombre) values ('BRIO. 153 VIV CASA');
insert into calles (nombre) values ('BRIO. 153 VIV. EDIF');
insert into calles (nombre) values ('BRIO. 154 VIV. EDIF');
insert into calles (nombre) values ('BRIO. 154 VIV.CASA');
insert into calles (nombre) values ('BRIO. 166 VIV.');
insert into calles (nombre) values ('BRIO. 169 VIV. CASA');
insert into calles (nombre) values ('BRIO. 169 VIV. EDIF');
insert into calles (nombre) values ('BRIO. 170 VIV. CASA');
insert into calles (nombre) values ('BRIO. 170 VIV. EDIF');
insert into calles (nombre) values ('BRIO. 181 VIV. CASA');
insert into calles (nombre) values ('BRIO. 181 VIV. EDIF');
insert into calles (nombre) values ('BRIO. 2 DE ABRIL');
insert into calles (nombre) values ('BRIO. 204 VIV. CASA');
insert into calles (nombre) values ('BRIO. 204 VIV. EDIF');
insert into calles (nombre) values ('BRIO. 218 VIV. -AYELEN - CASA');
insert into calles (nombre) values ('BRIO. 218 VIV. EDIF');
insert into calles (nombre) values ('BRIO. 3 DE JUNIO');
insert into calles (nombre) values ('BRIO. 30 VIV. CASA');
insert into calles (nombre) values ('BRIO. 30 VIV. EDIF.');
insert into calles (nombre) values ('BRIO. 32 VIV. CASA');
insert into calles (nombre) values ('BRIO. 34 HECTAREAS');
insert into calles (nombre) values ('BRIO. 40 VIV. CASA');
insert into calles (nombre) values ('BRIO. 400 VIV. CASA');
insert into calles (nombre) values ('BRIO. 60 VIV. CASA');
insert into calles (nombre) values ('BRIO. 76 VIVIENDAS (CIRCUNVALACION)');
insert into calles (nombre) values ('BRIO. 78 VIV. CASA');
insert into calles (nombre) values ('BRIO. 80 VIV-CO.VITUR');
insert into calles (nombre) values ('BRIO. 84 VIV. (SAN FRANCISCO I ) ESCAL.');
insert into calles (nombre) values ('BRIO. 96 VIV. (AMANCAY) CASA');
insert into calles (nombre) values ('BRIO. ADA M. ELFLEIN');
insert into calles (nombre) values ('BRIO. ALBORADA CASA');
insert into calles (nombre) values ('BRIO. ARELAUQUEN');
insert into calles (nombre) values ('BRIO. ARGENTINO');
insert into calles (nombre) values ('BRIO. CALFU RUCA');
insert into calles (nombre) values ('BRIO. CO.VI.BAR. (LA HABANA) CASA');
insert into calles (nombre) values ('BRIO. COOP. EL MAITEN');
insert into calles (nombre) values ('BRIO. ESTACION');
insert into calles (nombre) values ('BRIO. FRUTILLAR');
insert into calles (nombre) values ('BRIO. LAS VICTORIAS');
insert into calles (nombre) values ('BRIO. LEVALLE');
insert into calles (nombre) values ('BRIO. NAHUEL HUE');
insert into calles (nombre) values ('BRIO. VURILOCHE I CASA');
insert into calles (nombre) values ('BRIO. VURILOCHE IV CASA');
insert into calles (nombre) values ('BRIO.136 VIV.CASA');
insert into calles (nombre) values ('BRIO.199 VIV. CASA');
insert into calles (nombre) values ('BRIO.270 VIV. ( SAN FRANCISCO IV ) CASA');
insert into calles (nombre) values ('BRIO.28 DE ABRIL');
insert into calles (nombre) values ('BRIO.37 VIV.');
insert into calles (nombre) values ('BRIO.44 VIVIENDAS - CASA DE PIEDRA');
insert into calles (nombre) values ('BRIO.645 VIVIENDAS');
insert into calles (nombre) values ('BRIO.EL CONDOR COVITUR');
insert into calles (nombre) values ('BRIO.EL PINAR-S.F.IV');
insert into calles (nombre) values ('BRIO.EVA PERON');
insert into calles (nombre) values ('BUENOS AIRES');
insert into calles (nombre) values ('C. ALTOS DEL ESTE 10');
insert into calles (nombre) values ('C. ALTOS DEL ESTE 11');
insert into calles (nombre) values ('C. ALTOS DEL ESTE 4');
insert into calles (nombre) values ('C. ALTOS DEL ESTE 6');
insert into calles (nombre) values ('C. ALTOS DEL ESTE 7');
insert into calles (nombre) values ('C. ALTOS DEL ESTE 8');
insert into calles (nombre) values ('C/ ALTOS DEL ESTE 5');
insert into calles (nombre) values ('CABALLERO DE LA MONTAÑA TTE. 1° PEREYRA');
insert into calles (nombre) values ('CABALLO ALAZAN');
insert into calles (nombre) values ('CABALLO AZABACHE');
insert into calles (nombre) values ('CABALLO MORO');
insert into calles (nombre) values ('CABALLO TOBIANO');
insert into calles (nombre) values ('CABALLO TORDILLO');
insert into calles (nombre) values ('CABALLO ZAINO');
insert into calles (nombre) values ('CABILDO');
insert into calles (nombre) values ('CABO HECTOR OVIEDO');
insert into calles (nombre) values ('CABO MANUEL RAMON CAMPOS');
insert into calles (nombre) values ('CABO MIGUEL AVILA');
insert into calles (nombre) values ('CABO OSCAR LABALTA');
insert into calles (nombre) values ('CABURE');
insert into calles (nombre) values ('CACHALOTE PARDO');
insert into calles (nombre) values ('CACHAÑA');
insert into calles (nombre) values ('CACHUDITO PICO NEGRO');
insert into calles (nombre) values ('CACIQUE CALFUCURA');
insert into calles (nombre) values ('CACIQUE CASIMIRO');
insert into calles (nombre) values ('CACIQUE CHOCORI');
insert into calles (nombre) values ('CACIQUE CUMBAY');
insert into calles (nombre) values ('CACIQUE HUICALEO');
insert into calles (nombre) values ('CACIQUE NAHUEL');
insert into calles (nombre) values ('CACIQUE PRAFIL');
insert into calles (nombre) values ('CACIQUE PRAYEL');
insert into calles (nombre) values ('CACIQUE PURRAN');
insert into calles (nombre) values ('CADILLO');
insert into calles (nombre) values ('CAHUIL');
insert into calles (nombre) values ('CALAFATE');
insert into calles (nombre) values ('CALAFATE-DINA HUAPI');
insert into calles (nombre) values ('CALAFATILLO');
insert into calles (nombre) values ('CALAMARES');
insert into calles (nombre) values ('CALANDRIA MORA');
insert into calles (nombre) values ('CALENDULAS');
insert into calles (nombre) values ('CALEU CALEU');
insert into calles (nombre) values ('CALFU CO');
insert into calles (nombre) values ('CALLAO');
insert into calles (nombre) values ('CALLE 1');
insert into calles (nombre) values ('CALLE 1 (SAN FRANCISCO)');
insert into calles (nombre) values ('CALLE 10 - 645 VIVIENDAS');
insert into calles (nombre) values ('CALLE 10-C.DE PIEDRA');
insert into calles (nombre) values ('CALLE 12');
insert into calles (nombre) values ('CALLE 13 B.C.DE PIED');
insert into calles (nombre) values ('CALLE 17 - B.LOS NOTROS');
insert into calles (nombre) values ('CALLE 2 (SAN FRANCISCO)');
insert into calles (nombre) values ('CALLE 2 B.C.D.PIEDRA');
insert into calles (nombre) values ('CALLE 2 BARRIO 260 VIVIENDAS');
insert into calles (nombre) values ('CALLE 2 BARRIO 270 VIVIENDAS');
insert into calles (nombre) values ('CALLE 3');
insert into calles (nombre) values ('CALLE 3 (SAN FRANCISCO)');
insert into calles (nombre) values ('CALLE 3 BRIO. 270 VIV.');
insert into calles (nombre) values ('CALLE 4');
insert into calles (nombre) values ('CALLE 4 (SAN FRANCISCO)');
insert into calles (nombre) values ('CALLE 4B.CASA DE PIE');
insert into calles (nombre) values ('CALLE 5 - 130 VIV');
insert into calles (nombre) values ('CALLE 5 (SAN FRANCISCO)');
insert into calles (nombre) values ('CALLE 6');
insert into calles (nombre) values ('CALLE 6 (SAN FRANCISCO)');
insert into calles (nombre) values ('CALLE 6 C DE PIEDRA/2 DE AGOSTO');
insert into calles (nombre) values ('CALLE 7 - B. 169 VIV.');
insert into calles (nombre) values ('CALLE 7 C DE PIEDRA');
insert into calles (nombre) values ('CALLE 8 - 645 VIVIENDAS');
insert into calles (nombre) values ('CALLE 9');
insert into calles (nombre) values ('CALLE DIECINUEVE - BRIO. LOS NOTROS');
insert into calles (nombre) values ('CALLFU - CO');
insert into calles (nombre) values ('CALQUIN NORTE');
insert into calles (nombre) values ('CALQUIN SUR');
insert into calles (nombre) values ('CAMILO GARZA');
insert into calles (nombre) values ('CAMILO GOYE');
insert into calles (nombre) values ('CAMINO A CATEDRAL');
insert into calles (nombre) values ('CAMINO AL CHALLHUACO KM');
insert into calles (nombre) values ('CAMPICHUELO');
insert into calles (nombre) values ('CANARIO');
insert into calles (nombre) values ('CANARIO -BRIO. UNION');
insert into calles (nombre) values ('CANASTERO PATAGONICO');
insert into calles (nombre) values ('CANDIDO LOPEZ');
insert into calles (nombre) values ('CAÑADA');
insert into calles (nombre) values ('CAPITAN FERNANDO CASADO');
insert into calles (nombre) values ('CARACAS');
insert into calles (nombre) values ('CARANCA');
insert into calles (nombre) values ('CARANCHO ARAUCANO');
insert into calles (nombre) values ('CARLOS ARTURO COHEN');
insert into calles (nombre) values ('CARLOS GUIDO SPANO');
insert into calles (nombre) values ('CARLOS MANUEL BUSTOS');
insert into calles (nombre) values ('CARLOS MOREL');
insert into calles (nombre) values ('CARLOS NOWOTUY');
insert into calles (nombre) values ('CARLOS RUIZ');
insert into calles (nombre) values ('CARMEN DE PATAGONES');
insert into calles (nombre) values ('CARPINTERO ARAUCANO');
insert into calles (nombre) values ('CARPINTEROS');
insert into calles (nombre) values ('CASTAÑARES');
insert into calles (nombre) values ('CATAMARCA');
insert into calles (nombre) values ('CATEDRAL');
insert into calles (nombre) values ('CAUQUEN REAL');
insert into calles (nombre) values ('CAYU');
insert into calles (nombre) values ('CEDRO');
insert into calles (nombre) values ('CEFERINO NAMUNCURA');
insert into calles (nombre) values ('CEIBO');
insert into calles (nombre) values ('CELES');
insert into calles (nombre) values ('CENTAURO');
insert into calles (nombre) values ('CENTINELA');
insert into calles (nombre) values ('CENTINELAS DEL BOSQUE');
insert into calles (nombre) values ('CENTRO ATOMICO');
insert into calles (nombre) values ('CENTRO CIVICO');
insert into calles (nombre) values ('CERRO BAYO');
insert into calles (nombre) values ('CERRO BELLA VISTA');
insert into calles (nombre) values ('CERRO BLANCO');
insert into calles (nombre) values ('CERRO CARBON');
insert into calles (nombre) values ('CERRO CHALLHUACO');
insert into calles (nombre) values ('CERRO CHENQUE');
insert into calles (nombre) values ('CERRO CHICO');
insert into calles (nombre) values ('CERRO CONFLUENCIA');
insert into calles (nombre) values ('CERRO DE LOS CANTAROS');
insert into calles (nombre) values ('CERRO DEL VIENTO');
insert into calles (nombre) values ('CERRO EL HERMANO');
insert into calles (nombre) values ('CERRO FIA');
insert into calles (nombre) values ('CERRO LEON');
insert into calles (nombre) values ('CERRO LOPEZ');
insert into calles (nombre) values ('CERRO MESA');
insert into calles (nombre) values ('CERRO MILLAQUEO');
insert into calles (nombre) values ('CERRO MIRADOR');
insert into calles (nombre) values ('CERRO OTTO');
insert into calles (nombre) values ('CERRO PANTOJO');
insert into calles (nombre) values ('CERRO RUNGE');
insert into calles (nombre) values ('CERRO UTNE');
insert into calles (nombre) values ('CERRO VENTANA');
insert into calles (nombre) values ('CERRO VILLEGAS');
insert into calles (nombre) values ('CESAR MILSTEIN');
insert into calles (nombre) values ('CESAREO BERNALDO DE QUIROS');
insert into calles (nombre) values ('CHACABUCO');
insert into calles (nombre) values ('CHACAY');
insert into calles (nombre) values ('CHACAY HUA RUCA');
insert into calles (nombre) values ('CHACAY, DINA HUAPI');
insert into calles (nombre) values ('CHACO');
insert into calles (nombre) values ('CHAPEL');
insert into calles (nombre) values ('CHAPELQUITO');
insert into calles (nombre) values ('CHARCAO');
insert into calles (nombre) values ('CHAURA');
insert into calles (nombre) values ('CHENQUENIYEN');
insert into calles (nombre) values ('CHIGUAY JUAN Y FCO. (PLAZA)');
insert into calles (nombre) values ('CHILCO');
insert into calles (nombre) values ('CHILCO, DINA HUAPI, RÍO NEGRO');
insert into calles (nombre) values ('CHILE, DINA HUAPI');
insert into calles (nombre) values ('CHIMANGO');
insert into calles (nombre) values ('CHIN CHIN');
insert into calles (nombre) values ('CHINGOLOS');
insert into calles (nombre) values ('CHOELE CHOEL');
insert into calles (nombre) values ('CHOIQUE');
insert into calles (nombre) values ('CHOPIN');
insert into calles (nombre) values ('CHUBUT');
insert into calles (nombre) values ('CHURRIN ANDINO');
insert into calles (nombre) values ('CINCO ( QUECHU)');
insert into calles (nombre) values ('CINCO SALTOS');
insert into calles (nombre) values ('CIPOLLETTI');
insert into calles (nombre) values ('CIPRES, DINA HUAPI');
insert into calles (nombre) values ('CIPRESES - Bº ARRAYANES');
insert into calles (nombre) values ('CIRCUITO CHICO');
insert into calles (nombre) values ('CLAUDE MONET');
insert into calles (nombre) values ('CLAUDIO BERNAL');
insert into calles (nombre) values ('CLAVELINAS');
insert into calles (nombre) values ('CLEMENTE ONELLI');
insert into calles (nombre) values ('CO.VI.TUR. 5');
insert into calles (nombre) values ('CO.VI.TUR. A 4');
insert into calles (nombre) values ('CO.VI.TUR. A1');
insert into calles (nombre) values ('CO.VI.TUR. A2');
insert into calles (nombre) values ('CO.VI.TUR. A3');
insert into calles (nombre) values ('CO.VI.TUR. B.9');
insert into calles (nombre) values ('CO.VI.TUR. B7');
insert into calles (nombre) values ('CO.VI.TUR. B8');
insert into calles (nombre) values ('COHALA');
insert into calles (nombre) values ('COIRON');
insert into calles (nombre) values ('COLECTORA DIEGO NEIL');
insert into calles (nombre) values ('COLIHUE-MELIPAL');
insert into calles (nombre) values ('COLOMBIA');
insert into calles (nombre) values ('COLONIA');
insert into calles (nombre) values ('COLUDITO');
insert into calles (nombre) values ('COMANDANTE LUIS PIEDRABUENA');
insert into calles (nombre) values ('COMBATE DE LOS POZOS');
insert into calles (nombre) values ('COMBATE DE RIO SANTIAGO');
insert into calles (nombre) values ('COMBATE DE SAN CARLOS');
insert into calles (nombre) values ('COMBATE DEL BUCEO');
insert into calles (nombre) values ('COMBATIENTES');
insert into calles (nombre) values ('COMBERA');
insert into calles (nombre) values ('CON-CON');
insert into calles (nombre) values ('CONCEPCION');
insert into calles (nombre) values ('CONDORES');
insert into calles (nombre) values ('CONRADO MOLINA');
insert into calles (nombre) values ('COOPERATIVA QUIMEY RUCA');
insert into calles (nombre) values ('COPAHUE');
insert into calles (nombre) values ('COPIHUE');
insert into calles (nombre) values ('CORMORAN');
insert into calles (nombre) values ('CORNELIO DE SAAVEDRA');
insert into calles (nombre) values ('CORRALITO');
insert into calles (nombre) values ('CORRIENTES');
insert into calles (nombre) values ('CORRIENTES -MELIPAL');
insert into calles (nombre) values ('CORVINA');
insert into calles (nombre) values ('COSCOROBA');
insert into calles (nombre) values ('COSTA RICA (DINA HUAPI)');
insert into calles (nombre) values ('COTORRA');
insert into calles (nombre) values ('CRISTIAN HANSEN, DINA HUAPI');
insert into calles (nombre) values ('CRUCERO GENERAL BELGRANO');
insert into calles (nombre) values ('CRUZ DEL SUR');
insert into calles (nombre) values ('CUATRO (MELI )');
insert into calles (nombre) values ('CUBA');
insert into calles (nombre) values ('CUMBRE CERRO OTTO');
insert into calles (nombre) values ('CURAPALIHUE');
insert into calles (nombre) values ('CUREU');
insert into calles (nombre) values ('CURUZU CUATIA');
insert into calles (nombre) values ('CUYE');
insert into calles (nombre) values ('DE LA BRISA');
insert into calles (nombre) values ('DE LA BRUMA');
insert into calles (nombre) values ('DE LA CENTELLA');
insert into calles (nombre) values ('DE LA CRECIENTE');
insert into calles (nombre) values ('DE LA ESCARCHA');
insert into calles (nombre) values ('DE LA GARUA');
insert into calles (nombre) values ('DE LA HELADA');
insert into calles (nombre) values ('DE LA LLOVIZNA');
insert into calles (nombre) values ('DE LA NEBLINA');
insert into calles (nombre) values ('DE LA NEVADA');
insert into calles (nombre) values ('DE LA NEVISCA');
insert into calles (nombre) values ('DE LA RIBERA');
insert into calles (nombre) values ('DE LA TEMPESTAD');
insert into calles (nombre) values ('DE LA TORMENTA');
insert into calles (nombre) values ('DE LA VENTISCA');
insert into calles (nombre) values ('DE LAS BARDANAS');
insert into calles (nombre) values ('DE LAS CAMELIAS');
insert into calles (nombre) values ('DE LAS ESTRELLAS');
insert into calles (nombre) values ('DE LAS FRAMBUESAS');
insert into calles (nombre) values ('DE LAS FRUTILLAS');
insert into calles (nombre) values ('DE LAS GROSELLAS');
insert into calles (nombre) values ('DE LAS JARRILLAS');
insert into calles (nombre) values ('DE LAS LENGAS - VILLA CAMPANARIO-');
insert into calles (nombre) values ('DE LAS MADRESELVAS');
insert into calles (nombre) values ('DE LAS MALVAS');
insert into calles (nombre) values ('DE LAS MARGARITAS');
insert into calles (nombre) values ('DE LAS MELOSAS');
insert into calles (nombre) values ('DE LAS MORAS');
insert into calles (nombre) values ('DE LAS MOSQUETAS');
insert into calles (nombre) values ('DE LAS NEMESIAS');
insert into calles (nombre) values ('DE LAS RETAMAS');
insert into calles (nombre) values ('DE LAS ROMASAS');
insert into calles (nombre) values ('DE LOS ABEDULES');
insert into calles (nombre) values ('DE LOS AMANCAY');
insert into calles (nombre) values ('DE LOS ARANDANOS');
insert into calles (nombre) values ('DE LOS ARCES');
insert into calles (nombre) values ('DE LOS ARRAYANES');
insert into calles (nombre) values ('DE LOS ASTROS');
insert into calles (nombre) values ('DE LOS BUCHU');
insert into calles (nombre) values ('DE LOS BUHOS');
insert into calles (nombre) values ('DE LOS CERASTIOS');
insert into calles (nombre) values ('DE LOS CERROS');
insert into calles (nombre) values ('DE LOS CIPRESES NORTE');
insert into calles (nombre) values ('DE LOS CIPRESES SUR');
insert into calles (nombre) values ('DE LOS COIHUES');
insert into calles (nombre) values ('DE LOS COMETAS');
insert into calles (nombre) values ('DE LOS CORINTOS');
insert into calles (nombre) values ('DE LOS COYPOS');
insert into calles (nombre) values ('DE LOS CUYES');
insert into calles (nombre) values ('DE LOS ENEBROS');
insert into calles (nombre) values ('DE LOS ESPINOS');
insert into calles (nombre) values ('DE LOS GERANIOS');
insert into calles (nombre) values ('DE LOS GLACIARES');
insert into calles (nombre) values ('DE LOS GUINDOS');
insert into calles (nombre) values ('DE LOS HELECHOS');
insert into calles (nombre) values ('DE LOS HELIOTROPOS');
insert into calles (nombre) values ('DE LOS HIPERICOS');
insert into calles (nombre) values ('DE LOS LAGOS');
insert into calles (nombre) values ('DE LOS MAITENES - MELIPAL -');
insert into calles (nombre) values ('DE LOS MANZANOS');
insert into calles (nombre) values ('DE LOS MICHAY');
insert into calles (nombre) values ('DE LOS MIMBRES');
insert into calles (nombre) values ('DE LOS NOTROS');
insert into calles (nombre) values ('DE LOS PAÑILES');
insert into calles (nombre) values ('DE LOS PEINECILLOS');
insert into calles (nombre) values ('DE LOS PLANETAS');
insert into calles (nombre) values ('DE LOS PUMAS');
insert into calles (nombre) values ('DE LOS SATELITES');
insert into calles (nombre) values ('DE LOS TEPU');
insert into calles (nombre) values ('DE LOS ZORZALES');
insert into calles (nombre) values ('DEL AGUA NIEVE');
insert into calles (nombre) values ('DEL ALTO');
insert into calles (nombre) values ('DEL AMANECER');
insert into calles (nombre) values ('DEL ARCO IRIS');
insert into calles (nombre) values ('DEL ARROYO');
insert into calles (nombre) values ('DEL BAJO');
insert into calles (nombre) values ('DEL CAIQUEN');
insert into calles (nombre) values ('DEL CENIT');
insert into calles (nombre) values ('DEL CERRO');
insert into calles (nombre) values ('DEL CHAPARRON');
insert into calles (nombre) values ('DEL CHUCAO');
insert into calles (nombre) values ('DEL CORMORAN');
insert into calles (nombre) values ('DEL CREPUSCULO');
insert into calles (nombre) values ('DEL ESTE II (PROVISORIO)');
insert into calles (nombre) values ('DEL HUILLIN');
insert into calles (nombre) values ('DEL HURON');
insert into calles (nombre) values ('DEL MEDIO');
insert into calles (nombre) values ('DEL PERRO NEGRO');
insert into calles (nombre) values ('DEL PERU, DINA HUAPI');
insert into calles (nombre) values ('DEL PILQUIN');
insert into calles (nombre) values ('DEL QUISCO');
insert into calles (nombre) values ('DEL RAYO');
insert into calles (nombre) values ('DEL RELAMPAGO');
insert into calles (nombre) values ('DEL REMANSO');
insert into calles (nombre) values ('DEL ROCIO');
insert into calles (nombre) values ('DEL TAPACOLA');
insert into calles (nombre) values ('DEL TORRENTE');
insert into calles (nombre) values ('DEL VIENTO');
insert into calles (nombre) values ('DIAGONAL JUAN M. GUTIERREZ');
insert into calles (nombre) values ('DIAGONAL PRIMO CAPRARO');
insert into calles (nombre) values ('DIECINUEVE ( MARI AYLLA)');
insert into calles (nombre) values ('DIECISIETE ( MARI REGLE)');
insert into calles (nombre) values ('DIEZ (MARI)');
insert into calles (nombre) values ('DIUCAS');
insert into calles (nombre) values ('DIUCON');
insert into calles (nombre) values ('DOCTOR ANGEL GALLARDO');
insert into calles (nombre) values ('DOCTOR BAILEY WILLIS');
insert into calles (nombre) values ('DOCTOR JOHN O CONNOR');
insert into calles (nombre) values ('DOCTOR JUAN JAVIER NEUMEYER');
insert into calles (nombre) values ('DOCTOR OSCAR FERMIN LAPALMA');
insert into calles (nombre) values ('DOMINGO FAUSTINO SARMIENTO');
insert into calles (nombre) values ('DOMINGO FERNANDEZ BESCHTEDT');
insert into calles (nombre) values ('DOMINGO FRENCH');
insert into calles (nombre) values ('DON ALGUETA');
insert into calles (nombre) values ('DON ANGEL GELAIN');
insert into calles (nombre) values ('DON BOSCO');
insert into calles (nombre) values ('DOS (EPU)');
insert into calles (nombre) values ('DOS DE AGOSTO');
insert into calles (nombre) values ('DOS ISLAS');
insert into calles (nombre) values ('EAGLE');
insert into calles (nombre) values ('ECUADOR, DINA HUAPI');
insert into calles (nombre) values ('EDUARDO ELORDI');
insert into calles (nombre) values ('EDUARDO MALLEA');
insert into calles (nombre) values ('EDUARDO MAY');
insert into calles (nombre) values ('EDUARDO SIVORI');
insert into calles (nombre) values ('EDUCACION PUBLICA');
insert into calles (nombre) values ('EJERCITO');
insert into calles (nombre) values ('EL ATARDECER');
insert into calles (nombre) values ('EL BOLSON');
insert into calles (nombre) values ('EL CANELO');
insert into calles (nombre) values ('EL CUY');
insert into calles (nombre) values ('EL DORADO');
insert into calles (nombre) values ('EL FILO');
insert into calles (nombre) values ('EL LAZO');
insert into calles (nombre) values ('EL MICHAY, DINA HUAPI');
insert into calles (nombre) values ('EL MIRADOR');
insert into calles (nombre) values ('EL MIRADOR DEL NORTE');
insert into calles (nombre) values ('EL MIRADOR DEL SUR');
insert into calles (nombre) values ('EL OBRADOR');
insert into calles (nombre) values ('EL PAÑIL');
insert into calles (nombre) values ('EL ROSARIO');
insert into calles (nombre) values ('EL TAIQUE');
insert into calles (nombre) values ('EL TERO');
insert into calles (nombre) values ('EL VENTANA');
insert into calles (nombre) values ('ELECTRA');
insert into calles (nombre) values ('ELOISA MESA');
insert into calles (nombre) values ('ELORDI - Bº ARRAYANES');
insert into calles (nombre) values ('ELUNEY');
insert into calles (nombre) values ('EMILIO FREY');
insert into calles (nombre) values ('EMILIO HERNANDEZ (CAMINO ACC. CERRO OTTO');
insert into calles (nombre) values ('EMILIO MORALES');
insert into calles (nombre) values ('EMILIO PETTORUTI');
insert into calles (nombre) values ('ENRIQUE HERMITE');
insert into calles (nombre) values ('ENTRADA AL CHALHUACO');
insert into calles (nombre) values ('ERNESTO DE LA CARCOBA');
insert into calles (nombre) values ('ERNESTO SERIGOS');
insert into calles (nombre) values ('ESMERALDA');
insert into calles (nombre) values ('ESPAÑA');
insert into calles (nombre) values ('ESQUEL');
insert into calles (nombre) values ('ESTADOS UNIDOS, DINA HUAPI');
insert into calles (nombre) values ('ESTAFETA COLONIA SUI');
insert into calles (nombre) values ('ESTAFETA FRUTILLAR');
insert into calles (nombre) values ('ESTAFETA LLAO LLAO');
insert into calles (nombre) values ('ESTAFETA LOS COIHUES');
insert into calles (nombre) values ('ESTAFETA MASCARDI');
insert into calles (nombre) values ('ESTRELLA FEDERAL');
insert into calles (nombre) values ('EUCALIPTO');
insert into calles (nombre) values ('EUFRASIA');
insert into calles (nombre) values ('EUZKADI');
insert into calles (nombre) values ('EVARISTO CARRIEGO');
insert into calles (nombre) values ('FAIRWAY');
insert into calles (nombre) values ('FANNY T. DE NEWBERY');
insert into calles (nombre) values ('FEDERICO MOLINELLI');
insert into calles (nombre) values ('FELIX GOYE');
insert into calles (nombre) values ('FENIX');
insert into calles (nombre) values ('FERNANDO FADER');
insert into calles (nombre) values ('FIO - FIO');
insert into calles (nombre) values ('FITA RUIN');
insert into calles (nombre) values ('FLAMENCO AUSTRAL');
insert into calles (nombre) values ('FLORIDA S. FCO. IV');
insert into calles (nombre) values ('FORMOSA');
insert into calles (nombre) values ('FORTUNATO LACAMERA');
insert into calles (nombre) values ('FOYEL');
insert into calles (nombre) values ('FRANCIA');
insert into calles (nombre) values ('FRANCISCO CAFFERATTA');
insert into calles (nombre) values ('FRANCISCO DE BIEDMA');
insert into calles (nombre) values ('FRANCISCO JERMAN');
insert into calles (nombre) values ('FRANCISCO JORDI OLIVERAS');
insert into calles (nombre) values ('FRANCISCO LUIS BERNARDEZ');
insert into calles (nombre) values ('FRAY LUIS BELTRAN');
insert into calles (nombre) values ('FREY GUILLERMO BUTTLER');
insert into calles (nombre) values ('FUERA DE RADIO');
insert into calles (nombre) values ('FUINQUE');
insert into calles (nombre) values ('FULMAR');
insert into calles (nombre) values ('GALLARETA');
insert into calles (nombre) values ('GARIBALDI');
insert into calles (nombre) values ('GARZA BUEYERA');
insert into calles (nombre) values ('GAUGUIN PAUL');
insert into calles (nombre) values ('GAVILAN CENICIENTO');
insert into calles (nombre) values ('GAVIOTAS');
insert into calles (nombre) values ('GAVIOTIN');
insert into calles (nombre) values ('GENERAL ANTONIO TISCORNIA');
insert into calles (nombre) values ('GENERAL CONESA');
insert into calles (nombre) values ('GENERAL ENRIQUE MOSCONI');
insert into calles (nombre) values ('GENERAL NICOLAS PALACIOS');
insert into calles (nombre) values ('GENERAL ROCA');
insert into calles (nombre) values ('GENERAL SAN MARTIN - MELIPAL');
insert into calles (nombre) values ('GENERAL. CONRADO E. VILLEGAS');
insert into calles (nombre) values ('GENOVEVA BEVERAGGI');
insert into calles (nombre) values ('GEORGE MISIU');
insert into calles (nombre) values ('GIACOMO PUCCINI');
insert into calles (nombre) values ('GIRASOLES');
insert into calles (nombre) values ('GIUSEPPE VERDI');
insert into calles (nombre) values ('GLACIAR ALERCE');
insert into calles (nombre) values ('GLACIAR CASTAÑO OVERO');
insert into calles (nombre) values ('GLACIAR DEL MANSO');
insert into calles (nombre) values ('GLACIAR FRIAS');
insert into calles (nombre) values ('GOBERNADOR LEON QUAGLIA');
insert into calles (nombre) values ('GOBERNADOR PAGANO');
insert into calles (nombre) values ('GOBERNADOR VERNET');
insert into calles (nombre) values ('GODESIAS');
insert into calles (nombre) values ('GOLFO SAN MATIAS');
insert into calles (nombre) values ('GOLONDRINAS');
insert into calles (nombre) values ('GORRION');
insert into calles (nombre) values ('GRAFITO');
insert into calles (nombre) values ('GREGORIO VIDELA');
insert into calles (nombre) values ('GUALEGUAYCHU');
insert into calles (nombre) values ('GUANAY');
insert into calles (nombre) values ('GUATEMALA');
insert into calles (nombre) values ('GUAYAQUIL');
insert into calles (nombre) values ('GUEVARA');
insert into calles (nombre) values ('GUILLERMO KROMER');
insert into calles (nombre) values ('GUSTAVO CUCHI LEGUIZAMON');
insert into calles (nombre) values ('HALCON PEREGRINO');
insert into calles (nombre) values ('HALCONCITO');
insert into calles (nombre) values ('HALLEY');
insert into calles (nombre) values ('HANS LAUER');
insert into calles (nombre) values ('HAROLDO CONTI');
insert into calles (nombre) values ('HECTOR BASALDUA');
insert into calles (nombre) values ('HELENA');
insert into calles (nombre) values ('HENRY FORD');
insert into calles (nombre) values ('HEROES DE MALVINAS (RUTA DE CIRCUNVALACI');
insert into calles (nombre) values ('HEROES DEL BELGRANO');
insert into calles (nombre) values ('HILARIO CUADROS');
insert into calles (nombre) values ('HOLANDA');
insert into calles (nombre) values ('HORACIO ANASAGASTI');
insert into calles (nombre) values ('HORACIO CRUZ');
insert into calles (nombre) values ('HORACIO FLAVIO LUELMO');
insert into calles (nombre) values ('HORACIO QUIROGA');
insert into calles (nombre) values ('HOYO 1');
insert into calles (nombre) values ('HOYO DE EPUYEN');
insert into calles (nombre) values ('HUA HUM');
insert into calles (nombre) values ('HUALA');
insert into calles (nombre) values ('HUELLA VERDE');
insert into calles (nombre) values ('HUEMUL');
insert into calles (nombre) values ('HUET - HUET');
insert into calles (nombre) values ('HUILICHES');
insert into calles (nombre) values ('HUILQUI (ZORZAL)');
insert into calles (nombre) values ('HUINCUL');
insert into calles (nombre) values ('HUITRAN');
insert into calles (nombre) values ('HUNGRIA');
insert into calles (nombre) values ('HUNOLD PEN');
insert into calles (nombre) values ('INACAYAL');
insert into calles (nombre) values ('INDEPENDENCIA');
insert into calles (nombre) values ('ISAIAS QUILAHUEQUE');
insert into calles (nombre) values ('ISIDORO RUIZ MORENO');
insert into calles (nombre) values ('ISLA CENTINELA');
insert into calles (nombre) values ('ISLA DE LAS GALLINAS');
insert into calles (nombre) values ('ISLA DEL TIGRE');
insert into calles (nombre) values ('ISLA GAVIOTA');
insert into calles (nombre) values ('ISLA HUEMUL');
insert into calles (nombre) values ('ISLA SOLEDAD');
insert into calles (nombre) values ('ISLA VICTORIA');
insert into calles (nombre) values ('ISLAS MALVINAS');
insert into calles (nombre) values ('ITALIA');
insert into calles (nombre) values ('ITATA (PASTOREO ABUNDANTE)');
insert into calles (nombre) values ('JACOBACCI');
insert into calles (nombre) values ('JAIME DAVALOS');
insert into calles (nombre) values ('JAMAICA');
insert into calles (nombre) values ('JEAN SIBELIUS');
insert into calles (nombre) values ('JILGUEROS');
insert into calles (nombre) values ('JORGE CAFRUNE');
insert into calles (nombre) values ('JORGE LUIS BORGES');
insert into calles (nombre) values ('JOSE ANTONIO BALSEIRO');
insert into calles (nombre) values ('JOSE ARNAUDO');
insert into calles (nombre) values ('JOSE HERNANDEZ');
insert into calles (nombre) values ('JOSE INGENIEROS');
insert into calles (nombre) values ('JOSE LUIS PEFAURE');
insert into calles (nombre) values ('JOSE LUKMAN');
insert into calles (nombre) values ('JOSE MARIA SOBRAL');
insert into calles (nombre) values ('JOSE OBRERO');
insert into calles (nombre) values ('JOSE PARRAVICCINI');
insert into calles (nombre) values ('JOSE PEDRONI');
insert into calles (nombre) values ('JOSE YOHTA SAITO');
insert into calles (nombre) values ('JOTE');
insert into calles (nombre) values ('JUAN BATTLE PLANAS');
insert into calles (nombre) values ('JUAN BAUTISTA MASSA');
insert into calles (nombre) values ('JUAN CARLOS CASTAGNINO');
insert into calles (nombre) values ('JUAN DEL PRETE');
insert into calles (nombre) values ('JUAN JOSE CASTRO');
insert into calles (nombre) values ('JUAN JOSE PASO');
insert into calles (nombre) values ('JUAN MARCOS HERMAN');
insert into calles (nombre) values ('JULIETA');
insert into calles (nombre) values ('JULIO ARGENTINO JEREZ');
insert into calles (nombre) values ('JULIO CORTAZAR');
insert into calles (nombre) values ('JUNCAL');
insert into calles (nombre) values ('JUNQUERO');
insert into calles (nombre) values ('JUNTA VECINAL');
insert into calles (nombre) values ('JURAMENTO');
insert into calles (nombre) values ('KAMERER');
insert into calles (nombre) values ('KEU');
insert into calles (nombre) values ('LA AVUTARDA');
insert into calles (nombre) values ('LA CANDELARIA');
insert into calles (nombre) values ('LA CANTERA');
insert into calles (nombre) values ('LA CASCADA');
insert into calles (nombre) values ('LA CODORNIZ');
insert into calles (nombre) values ('LA FLORIDA');
insert into calles (nombre) values ('LA FRAGUA');
insert into calles (nombre) values ('LA FRONTERA');
insert into calles (nombre) values ('LA HABANA');
insert into calles (nombre) values ('LA HIGUERA');
insert into calles (nombre) values ('LA HOYA');
insert into calles (nombre) values ('LA LECHUZA');
insert into calles (nombre) values ('LA MARTINA');
insert into calles (nombre) values ('LA MEDIALUNA');
insert into calles (nombre) values ('LA MORENA');
insert into calles (nombre) values ('LA PALMA');
insert into calles (nombre) values ('LA PALOMA');
insert into calles (nombre) values ('LA PASTO VERDE');
insert into calles (nombre) values ('LA PAZ');
insert into calles (nombre) values ('LA PRIMAVERA');
insert into calles (nombre) values ('LA ROTONDA');
insert into calles (nombre) values ('LA SEQUOIA');
insert into calles (nombre) values ('LA TELESITA');
insert into calles (nombre) values ('LAGO ARGENTINO');
insert into calles (nombre) values ('LAGO ESCONDIDO');
insert into calles (nombre) values ('LAGO ESPEJO');
insert into calles (nombre) values ('LAGO FALKNER');
insert into calles (nombre) values ('LAGO FONCK');
insert into calles (nombre) values ('LAGO GUILLELMO');
insert into calles (nombre) values ('LAGO GUTIERREZ');
insert into calles (nombre) values ('LAGO HESS');
insert into calles (nombre) values ('LAGO LACAR');
insert into calles (nombre) values ('LAGO MARTIN');
insert into calles (nombre) values ('LAGO MASCARDI');
insert into calles (nombre) values ('LAGO MORENO');
insert into calles (nombre) values ('LAGO NAHUEL HUAPI');
insert into calles (nombre) values ('LAGO ROCA');
insert into calles (nombre) values ('LAGO STEFFEN');
insert into calles (nombre) values ('LAGOS DEL SUR');
insert into calles (nombre) values ('LAGUNA FANTASMA');
insert into calles (nombre) values ('LAGUNA JAKOB');
insert into calles (nombre) values ('LAGUNA SCHMOLL');
insert into calles (nombre) values ('LAGUNA TONCKEK');
insert into calles (nombre) values ('LANCHA AVUTARDA');
insert into calles (nombre) values ('LANCHA CORMORAN');
insert into calles (nombre) values ('LANCHA CORRENTOSO');
insert into calles (nombre) values ('LANCHA CRISTINA');
insert into calles (nombre) values ('LANCHA CRUZ DEL SUR');
insert into calles (nombre) values ('LANCHA FLAMENCO');
insert into calles (nombre) values ('LANCHA HUEMUL');
insert into calles (nombre) values ('LANCHA JUANA DE ARCO');
insert into calles (nombre) values ('LANCHA PATAGONIA');
insert into calles (nombre) values ('LANCHA PILQUIN');
insert into calles (nombre) values ('LANIN');
insert into calles (nombre) values ('LAPACHO');
insert into calles (nombre) values ('LAPRIDA');
insert into calles (nombre) values ('LAS AGUILAS');
insert into calles (nombre) values ('LAS AMERICAS, DINA HUAPI');
insert into calles (nombre) values ('LAS BANDURRIAS (DINA HUAPI)');
insert into calles (nombre) values ('LAS BAYAS');
insert into calles (nombre) values ('LAS CAÑAS');
insert into calles (nombre) values ('LAS CODORNICES');
insert into calles (nombre) values ('LAS GAVIOTAS');
insert into calles (nombre) values ('LAS GOLONDRINAS-');
insert into calles (nombre) values ('LAS HUALAS');
insert into calles (nombre) values ('LAS LENGAS, DINA HUAPI');
insert into calles (nombre) values ('LAS LIEBRES');
insert into calles (nombre) values ('LAS MUTISIAS');
insert into calles (nombre) values ('LAS NALCAS');
insert into calles (nombre) values ('LAS ORQUIDEAS');
insert into calles (nombre) values ('LAS PALMAS');
insert into calles (nombre) values ('LAS PIRITAS');
insert into calles (nombre) values ('LAS ROCAS');
insert into calles (nombre) values ('LAS ROSAS');
insert into calles (nombre) values ('LAS TRES MARIAS');
insert into calles (nombre) values ('LAS VERTIENTES');
insert into calles (nombre) values ('LAS VIOLETAS');
insert into calles (nombre) values ('LAURA');
insert into calles (nombre) values ('LAUTARO');
insert into calles (nombre) values ('LECHUCITA PAMPA');
insert into calles (nombre) values ('LECHUZA');
insert into calles (nombre) values ('LENGA');
insert into calles (nombre) values ('LENGA - BRIO. ARRAYANES)');
insert into calles (nombre) values ('LEUCERIA');
insert into calles (nombre) values ('LIBERTAD');
insert into calles (nombre) values ('LIBRA');
insert into calles (nombre) values ('LICAN');
insert into calles (nombre) values ('LILINQUEN');
insert into calles (nombre) values ('LIMA');
insert into calles (nombre) values ('LIMAY');
insert into calles (nombre) values ('LINGUE');
insert into calles (nombre) values ('LINO SPILIMBERGO');
insert into calles (nombre) values ('LIONEL ERNESTO RIVAS FABBRI');
insert into calles (nombre) values ('LLANTEN');
insert into calles (nombre) values ('LOASA');
insert into calles (nombre) values ('LOBELIAS');
insert into calles (nombre) values ('LOICA');
insert into calles (nombre) values ('LOLA MORA');
insert into calles (nombre) values ('LONQUIMAY');
insert into calles (nombre) values ('LOS ALAMOS');
insert into calles (nombre) values ('LOS ALERCES');
insert into calles (nombre) values ('LOS ANDES');
insert into calles (nombre) values ('LOS ARRAYANES');
insert into calles (nombre) values ('LOS ARRAYANES, DINA HUAPI');
insert into calles (nombre) values ('LOS ARTESANOS');
insert into calles (nombre) values ('LOS AVELLANOS');
insert into calles (nombre) values ('LOS BERBEL');
insert into calles (nombre) values ('LOS CANTAROS');
insert into calles (nombre) values ('LOS CEREZOS');
insert into calles (nombre) values ('LOS CERRILLOS');
insert into calles (nombre) values ('LOS CHILCOS');
insert into calles (nombre) values ('LOS CHINCHINALES');
insert into calles (nombre) values ('LOS CHINCHINES');
insert into calles (nombre) values ('LOS CIPRESALES');
insert into calles (nombre) values ('LOS CIPRESES');
insert into calles (nombre) values ('LOS COHIUES');
insert into calles (nombre) values ('LOS COLIBRIS');
insert into calles (nombre) values ('LOS COLIHUES');
insert into calles (nombre) values ('LOS EUCALIPTOS');
insert into calles (nombre) values ('LOS GRILLOS');
insert into calles (nombre) values ('LOS HONGOS');
insert into calles (nombre) values ('LOS MAITENES - LAS VERTIENTES-');
insert into calles (nombre) values ('LOS MAITENES, DINA HUAPI');
insert into calles (nombre) values ('LOS MOLLES');
insert into calles (nombre) values ('LOS MUERDAGOS');
insert into calles (nombre) values ('LOS NOGALES-DINA HUA');
insert into calles (nombre) values ('LOS NOTROS');
insert into calles (nombre) values ('LOS NOTROS, DINA HUAPI');
insert into calles (nombre) values ('LOS ÑIRES');
insert into calles (nombre) values ('LOS ÑIRES, DINA HUAPI');
insert into calles (nombre) values ('LOS OLMOS');
insert into calles (nombre) values ('LOS PEHUENES');
insert into calles (nombre) values ('LOS PINGUINOS');
insert into calles (nombre) values ('LOS PINOS');
insert into calles (nombre) values ('LOS PINTORES');
insert into calles (nombre) values ('LOS POETAS');
insert into calles (nombre) values ('LOS PRUNUS');
insert into calles (nombre) values ('LOS PUMAS');
insert into calles (nombre) values ('LOS QUETROS');
insert into calles (nombre) values ('LOS RADALES');
insert into calles (nombre) values ('LOS RADALES, DINA HUAPI');
insert into calles (nombre) values ('LOS RETAMOS');
insert into calles (nombre) values ('LOS RETOÑOS');
insert into calles (nombre) values ('LOS ROBLES');
insert into calles (nombre) values ('LOS TILOS');
insert into calles (nombre) values ('LOS TORDOS');
insert into calles (nombre) values ('LOS TULIPANES');
insert into calles (nombre) values ('LUAN');
insert into calles (nombre) values ('LUAN NORTE');
insert into calles (nombre) values ('LUAN SUR');
insert into calles (nombre) values ('LUCERNA');
insert into calles (nombre) values ('LUCILIA');
insert into calles (nombre) values ('LUCIO CORREA MORALES');
insert into calles (nombre) values ('LUIS GIANNEO');
insert into calles (nombre) values ('LUIS MARCHIORI');
insert into calles (nombre) values ('LUIS SEDANE');
insert into calles (nombre) values ('LUISA RUNGE');
insert into calles (nombre) values ('LUMA');
insert into calles (nombre) values ('LUPINOS');
insert into calles (nombre) values ('MACÁ PLATEADO');
insert into calles (nombre) values ('MACEDA');
insert into calles (nombre) values ('MAGNOLIAS');
insert into calles (nombre) values ('MAHUIDA');
insert into calles (nombre) values ('MAITENES - BRIO. ARRAYANES -');
insert into calles (nombre) values ('MALVINA SOLEDAD');
insert into calles (nombre) values ('MANAGUA');
insert into calles (nombre) values ('MANDISOVI');
insert into calles (nombre) values ('MANIU');
insert into calles (nombre) values ('MANUEL ALBERTI');
insert into calles (nombre) values ('MANUEL GOMEZ CARRILLO');
insert into calles (nombre) values ('MAPUCHES');
insert into calles (nombre) values ('MAPUCHES - RANCHO GRANDE');
insert into calles (nombre) values ('MAQUI');
insert into calles (nombre) values ('MAQUINCHAO');
insert into calles (nombre) values ('MAR DEL PLATA');
insert into calles (nombre) values ('MARA (LIEBRE PATAGONICA)');
insert into calles (nombre) values ('MARI - ( DIEZ)');
insert into calles (nombre) values ('MARIA AYELEN');
insert into calles (nombre) values ('MARIA ELENA WALSH');
insert into calles (nombre) values ('MARIA EUGENIA');
insert into calles (nombre) values ('MARIA JOSE');
insert into calles (nombre) values ('MARÍA LUISA');
insert into calles (nombre) values ('MARIA PAOLA');
insert into calles (nombre) values ('MARIANO CASTEX');
insert into calles (nombre) values ('MARIANO MORENO- (EL FALDEO)');
insert into calles (nombre) values ('MARIANO MORES');
insert into calles (nombre) values ('MARTA LYNCH');
insert into calles (nombre) values ('MARTHA DE LOS RIOS');
insert into calles (nombre) values ('MARTIN FIERRO');
insert into calles (nombre) values ('MARTIN GARCIA');
insert into calles (nombre) values ('MARTIN JEREB');
insert into calles (nombre) values ('MARTIN MALHARRO');
insert into calles (nombre) values ('MARTIN MIGUEL DE GUEMES');
insert into calles (nombre) values ('MARTIN PESCADOR');
insert into calles (nombre) values ('MARTINETA');
insert into calles (nombre) values ('MEDALLITA');
insert into calles (nombre) values ('MEDIOEVO');
insert into calles (nombre) values ('MELI');
insert into calles (nombre) values ('MENDOZA');
insert into calles (nombre) values ('MERCEDES SOSA');
insert into calles (nombre) values ('MEXICO');
insert into calles (nombre) values ('MIAMI - S.FCO. IV');
insert into calles (nombre) values ('MICHAY - B* 28 DE ABRIL');
insert into calles (nombre) values ('MICHAY, MELIPAL');
insert into calles (nombre) values ('MIGUEL VICTORICA');
insert into calles (nombre) values ('MILANO BLANCO');
insert into calles (nombre) values ('MIRAMAR NORTE');
insert into calles (nombre) values ('MIRAMAR SUR');
insert into calles (nombre) values ('MISIONES');
insert into calles (nombre) values ('MISTO');
insert into calles (nombre) values ('MITRE - MELIPAL');
insert into calles (nombre) values ('MODESTA VICTORIA');
insert into calles (nombre) values ('MOLLE');
insert into calles (nombre) values ('MONSEÑOR ENRIQUE ANGELELLI');
insert into calles (nombre) values ('MONSEÑOR JOSE FAGNANO');
insert into calles (nombre) values ('MONSEÑOR NICOLAS ESANDI');
insert into calles (nombre) values ('MONTE MORO');
insert into calles (nombre) values ('MONTEVIDEO');
insert into calles (nombre) values ('MONUMENTO NATURAL BALLENA FRANCA');
insert into calles (nombre) values ('MONUMENTO NATURAL BOSQUE PETRIFICADO');
insert into calles (nombre) values ('MONUMENTO NATURAL LAGUNA POZUELOS');
insert into calles (nombre) values ('MOTITA');
insert into calles (nombre) values ('MOTONAVE HUILQUI');
insert into calles (nombre) values ('MOZART');
insert into calles (nombre) values ('MUTILLA');
insert into calles (nombre) values ('NAHUEL HUAPI');
insert into calles (nombre) values ('NAHUELQUIR');
insert into calles (nombre) values ('NAOS');
insert into calles (nombre) values ('NARCISOS');
insert into calles (nombre) values ('NECOCHEA');
insert into calles (nombre) values ('NEHUEN');
insert into calles (nombre) values ('NENEO');
insert into calles (nombre) values ('NESTOR KIRCHNER');
insert into calles (nombre) values ('NEUQUEN');
insert into calles (nombre) values ('NILPI');
insert into calles (nombre) values ('NILPI NORTE');
insert into calles (nombre) values ('NILPI SUR');
insert into calles (nombre) values ('NO ME OLVIDES');
insert into calles (nombre) values ('NUBES');
insert into calles (nombre) values ('NUESTRA SEÑORA DE LOURDES');
insert into calles (nombre) values ('NUESTRAS MALVINAS');
insert into calles (nombre) values ('NUEVA CONSTITUCION');
insert into calles (nombre) values ('NUEVE ( AYLLA)');
insert into calles (nombre) values ('NUEVE DE JULIO');
insert into calles (nombre) values ('ÑACURUTU');
insert into calles (nombre) values ('ÑANCU LAHUEN');
insert into calles (nombre) values ('ÑANDU');
insert into calles (nombre) values ('ÑORQUIN');
insert into calles (nombre) values ('ÑORQUINCO');
insert into calles (nombre) values ('OCHAVA');
insert into calles (nombre) values ('OCHO (PURRA)');
insert into calles (nombre) values ('OJO DE AGUA');
insert into calles (nombre) values ('OJOS DEL SALADO');
insert into calles (nombre) values ('ONAS');
insert into calles (nombre) values ('ONCE ( MARI QUIÑE)');
insert into calles (nombre) values ('ONURIS');
insert into calles (nombre) values ('ORION');
insert into calles (nombre) values ('OSCAR BERNARDO FELIX RUNGE');
insert into calles (nombre) values ('OSIRIS');
insert into calles (nombre) values ('OSORNO');
insert into calles (nombre) values ('OSTRAS');
insert into calles (nombre) values ('OSTRERO AUSTRAL');
insert into calles (nombre) values ('OTTO GOEDECKE');
insert into calles (nombre) values ('OTTO MEILING');
insert into calles (nombre) values ('PABLO COUDOUY');
insert into calles (nombre) values ('PABLO MANGE');
insert into calles (nombre) values ('PABLO MARIA BERUTTI');
insert into calles (nombre) values ('PADRE DIEGO DE ROSALES');
insert into calles (nombre) values ('PADRE ENRIQUE MONTEVERDE');
insert into calles (nombre) values ('PADRE FELIPE LAGUNA');
insert into calles (nombre) values ('PADRE FRANCISCO ELGUEA');
insert into calles (nombre) values ('PADRE JUAN JOSE GUILLELMO');
insert into calles (nombre) values ('PADRE MICHE');
insert into calles (nombre) values ('PADRE NICOLAS MASCARDI');
insert into calles (nombre) values ('PADRE ZACARIAS GENGHINI');
insert into calles (nombre) values ('PAICO');
insert into calles (nombre) values ('PAIHUEN');
insert into calles (nombre) values ('PAIMUN');
insert into calles (nombre) values ('PAJARO CARPINTERO');
insert into calles (nombre) values ('PAJAROS AZULES');
insert into calles (nombre) values ('PALO PICHE');
insert into calles (nombre) values ('PALO SANTO');
insert into calles (nombre) values ('PALOMA ARAUCANA');
insert into calles (nombre) values ('PAMPA DE BUENULEO');
insert into calles (nombre) values ('PAMPITA');
insert into calles (nombre) values ('PANAMA');
insert into calles (nombre) values ('PANGUE');
insert into calles (nombre) values ('PAÑIL');
insert into calles (nombre) values ('PARAISO');
insert into calles (nombre) values ('PARAMARIBO');
insert into calles (nombre) values ('PARAMELA');
insert into calles (nombre) values ('PARDELA');
insert into calles (nombre) values ('PARQUE NACIONAL ARRAYANES');
insert into calles (nombre) values ('PARQUE NACIONAL BARITU');
insert into calles (nombre) values ('PARQUE NACIONAL CALILEGUA');
insert into calles (nombre) values ('PARQUE NACIONAL DIAMANTE');
insert into calles (nombre) values ('PARQUE NACIONAL EL CHACO');
insert into calles (nombre) values ('PARQUE NACIONAL EL PALMAR');
insert into calles (nombre) values ('PARQUE NACIONAL EL REY');
insert into calles (nombre) values ('PARQUE NACIONAL IGUAZU');
insert into calles (nombre) values ('PARQUE NACIONAL LAGO PUELO');
insert into calles (nombre) values ('PARQUE NACIONAL LAGUNA BLANCA');
insert into calles (nombre) values ('PARQUE NACIONAL LANIN');
insert into calles (nombre) values ('PARQUE NACIONAL LIHUEL CALEL');
insert into calles (nombre) values ('PARQUE NACIONAL LOS ALERCES');
insert into calles (nombre) values ('PARQUE NACIONAL LOS GLACIARES');
insert into calles (nombre) values ('PARQUE NACIONAL NAHUEL HUAPI');
insert into calles (nombre) values ('PARQUE NACIONAL PERITO MORENO');
insert into calles (nombre) values ('PARQUE NACIONAL PILCOMAYO');
insert into calles (nombre) values ('PARQUE NACIONAL SIERRA DE LAS QUIJADAS');
insert into calles (nombre) values ('PARQUE NACIONAL TIERRA DEL FUEGO');
insert into calles (nombre) values ('PASAJE 17 DE AGOSTO');
insert into calles (nombre) values ('PASAJE DE LOS ANTIGUOS POBLADORES');
insert into calles (nombre) values ('PASAJE JUAN MARIA GUTIERREZ');
insert into calles (nombre) values ('PASAJE JUSTO JOSE DE URQUIZA');
insert into calles (nombre) values ('PASAJE MARGARITA PALACIOS');
insert into calles (nombre) values ('PASAJE VEINTIDOS DE ENERO');
insert into calles (nombre) values ('PASEO ALFREDO CASPANI');
insert into calles (nombre) values ('PASEO ANTUMALAL');
insert into calles (nombre) values ('PASEO DE LAS HILANDERAS');
insert into calles (nombre) values ('PASEO DE LOS AGUATEROS');
insert into calles (nombre) values ('PASEO DE LOS ARRIEROS');
insert into calles (nombre) values ('PASEO DE LOS ARTESANOS');
insert into calles (nombre) values ('PASEO DE LOS BAQUEANOS');
insert into calles (nombre) values ('PASEO DE LOS CARPINTEROS');
insert into calles (nombre) values ('PASEO DE LOS CERAMISTAS');
insert into calles (nombre) values ('PASEO DE LOS LEÑADORES');
insert into calles (nombre) values ('PASEO DE LOS LEONES');
insert into calles (nombre) values ('PASEO DE LOS ORFEBRES');
insert into calles (nombre) values ('PASEO DEL HURON');
insert into calles (nombre) values ('PASEO FUNDACION SARA MARIA FURMAN');
insert into calles (nombre) values ('PASO DE LOS MOLLES');
insert into calles (nombre) values ('PASO DE LOS VURILOCHES');
insert into calles (nombre) values ('PASO FLORES');
insert into calles (nombre) values ('PATAGONES -Bº R. GRANDE');
insert into calles (nombre) values ('PATAGONIA ARGENTINA, DINA HUAPI');
insert into calles (nombre) values ('PATAGUA');
insert into calles (nombre) values ('PATO OVERO');
insert into calles (nombre) values ('PEATONAL 2');
insert into calles (nombre) values ('PECHO COLORADO');
insert into calles (nombre) values ('PEDRO ALZATI');
insert into calles (nombre) values ('PEDRO DOMINGUEZ NEIRA');
insert into calles (nombre) values ('PEDRO GIACCHINO');
insert into calles (nombre) values ('PEHUEN');
insert into calles (nombre) values ('PEHUENCHES');
insert into calles (nombre) values ('PEHUENES');
insert into calles (nombre) values ('PEJERREY');
insert into calles (nombre) values ('PEÑI');
insert into calles (nombre) values ('PEONIAS');
insert into calles (nombre) values ('PEREZIA');
insert into calles (nombre) values ('PERITO FRANCISCO PASCACIO MORENO');
insert into calles (nombre) values ('PETREL');
insert into calles (nombre) values ('PETUNIAS');
insert into calles (nombre) values ('PEULLA');
insert into calles (nombre) values ('PEUTREN');
insert into calles (nombre) values ('PICAFLORES');
insert into calles (nombre) values ('PICHI MAHUIDA');
insert into calles (nombre) values ('PICHILENA');
insert into calles (nombre) values ('PICHINCHA');
insert into calles (nombre) values ('PICO DE PLATA');
insert into calles (nombre) values ('PICOLEZNA');
insert into calles (nombre) values ('PICUNCHES');
insert into calles (nombre) values ('PIEDRA DEL CONDOR');
insert into calles (nombre) values ('PIEDRAS');
insert into calles (nombre) values ('PIEDRAS BLANCAS');
insert into calles (nombre) values ('PIL PIL VOQUI');
insert into calles (nombre) values ('PILCANIYEU');
insert into calles (nombre) values ('PILQUIMAN');
insert into calles (nombre) values ('PINCEN');
insert into calles (nombre) values ('PINSA HUAPI');
insert into calles (nombre) values ('PINTACURA');
insert into calles (nombre) values ('PINTORES ARGENTINOS');
insert into calles (nombre) values ('PIRE-CO');
insert into calles (nombre) values ('PIREN (NIEVE)');
insert into calles (nombre) values ('PIREN MAHUIDA');
insert into calles (nombre) values ('PITIOS');
insert into calles (nombre) values ('POSTA DE YATASTO');
insert into calles (nombre) values ('PRILIDIANO PUEYRREDON');
insert into calles (nombre) values ('PRIMER TENIENTE DANIEL JUKIC');
insert into calles (nombre) values ('PRIMERA CORTADA');
insert into calles (nombre) values ('PRIMERA DIAGONAL');
insert into calles (nombre) values ('PRIMERA JUNTA');
insert into calles (nombre) values ('PRIMERO DE MAYO');
insert into calles (nombre) values ('PRIMEROS POBLADORES');
insert into calles (nombre) values ('PRIMULAS');
insert into calles (nombre) values ('PRION');
insert into calles (nombre) values ('PUCARA');
insert into calles (nombre) values ('PUDU');
insert into calles (nombre) values ('PUDU NORTE');
insert into calles (nombre) values ('PUDU SUR');
insert into calles (nombre) values ('PUE ( VOLVER)');
insert into calles (nombre) values ('PUELCHES');
insert into calles (nombre) values ('PUENTE VIEJO');
insert into calles (nombre) values ('PUERTO ALEGRE');
insert into calles (nombre) values ('PUERTO ANCHORENA');
insert into calles (nombre) values ('PUERTO ARGENTINO');
insert into calles (nombre) values ('PUERTO BLEST');
insert into calles (nombre) values ('PUERTO FRIAS');
insert into calles (nombre) values ('PUERTO PAÑUELO');
insert into calles (nombre) values ('PUERTO SAN CARLOS');
insert into calles (nombre) values ('PUERTO SPIEGEL');
insert into calles (nombre) values ('PUERTO TIGRE');
insert into calles (nombre) values ('PUNQUE');
insert into calles (nombre) values ('PUNTA NEVADA');
insert into calles (nombre) values ('PUNTA PRINCESA');
insert into calles (nombre) values ('PUYEHUE');
insert into calles (nombre) values ('QTA. 59');
insert into calles (nombre) values ('QUEBRACHO');
insert into calles (nombre) values ('QUECHU');
insert into calles (nombre) values ('QUEN QUEN TREU');
insert into calles (nombre) values ('QUEÑI');
insert into calles (nombre) values ('QUETRI');
insert into calles (nombre) values ('QUETRO AUSTRAL');
insert into calles (nombre) values ('QUILLEN (LUNA)');
insert into calles (nombre) values ('QUILMES');
insert into calles (nombre) values ('QUILPA');
insert into calles (nombre) values ('QUILPO');
insert into calles (nombre) values ('QUILPO SUR - NAHUEL MALAL');
insert into calles (nombre) values ('QUINCE ( MARI QUECHU)');
insert into calles (nombre) values ('QUINCHAHUALA');
insert into calles (nombre) values ('QUINCHAMALI');
insert into calles (nombre) values ('QUINTRAL');
insert into calles (nombre) values ('QUINTRAL, DINA HUAPI');
insert into calles (nombre) values ('QUIÑE (UNO)');
insert into calles (nombre) values ('QUITO');
insert into calles (nombre) values ('QUIULA');
insert into calles (nombre) values ('RAFAEL OBLIGADO');
insert into calles (nombre) values ('RAHUE');
insert into calles (nombre) values ('RALGUE');
insert into calles (nombre) values ('RAMON ENRIQUE GAVIOLA');
insert into calles (nombre) values ('RAMON GOMEZ CORNET');
insert into calles (nombre) values ('RAMSES');
insert into calles (nombre) values ('RANQUIL-CO');
insert into calles (nombre) values ('RANQUILEO');
insert into calles (nombre) values ('RAQUEL FORNER');
insert into calles (nombre) values ('RAQUI');
insert into calles (nombre) values ('RARAS');
insert into calles (nombre) values ('RAUL SOLDI');
insert into calles (nombre) values ('RAULI');
insert into calles (nombre) values ('RAULI, DINA HUAPI');
insert into calles (nombre) values ('RAWSON');
insert into calles (nombre) values ('RAYADITO');
insert into calles (nombre) values ('RECONQUISTA');
insert into calles (nombre) values ('RELMU');
insert into calles (nombre) values ('REMEDIOS ESCALADA DE SAN MARTIN');
insert into calles (nombre) values ('REMOLCADOR HELVECIA');
insert into calles (nombre) values ('REMOLCADOR LLAO-LLAO');
insert into calles (nombre) values ('REMOLINERA NEGRA');
insert into calles (nombre) values ('RESERVA NATURAL ESTRICTA OTAMENDI');
insert into calles (nombre) values ('RESERVA NATURAL ESTRICTA SAN ANTONIO');
insert into calles (nombre) values ('RESERVA NATURAL FORMOSA');
insert into calles (nombre) values ('REYNALDO ANTUNEZ');
insert into calles (nombre) values ('RICARDO GUIRALDES');
insert into calles (nombre) values ('RICARDO ROJAS');
insert into calles (nombre) values ('RIGEL');
insert into calles (nombre) values ('RIO AZUL');
insert into calles (nombre) values ('RIO CALEUFU');
insert into calles (nombre) values ('RIO CASTAÑO OVERO');
insert into calles (nombre) values ('RIO CORRENTOSO');
insert into calles (nombre) values ('RIO CUYIN MANZANO');
insert into calles (nombre) values ('RÍO DE REYES');
insert into calles (nombre) values ('RIO FOYEL');
insert into calles (nombre) values ('RIO GALLEGOS');
insert into calles (nombre) values ('RIO MANSO');
insert into calles (nombre) values ('RIO MINERO');
insert into calles (nombre) values ('RIO ÑIRIHUAO');
insert into calles (nombre) values ('RIO PICHILEUFU');
insert into calles (nombre) values ('RIO TURBIO');
insert into calles (nombre) values ('RIO VILLEGAS');
insert into calles (nombre) values ('RIOBAMBA');
insert into calles (nombre) values ('ROBERTO ARLT');
insert into calles (nombre) values ('ROBLES PELLIN');
insert into calles (nombre) values ('ROBUSTINA BOOCK');
insert into calles (nombre) values ('ROCA NEGRA');
insert into calles (nombre) values ('RODOLFO WALSH');
insert into calles (nombre) values ('ROMERILLO');
insert into calles (nombre) values ('ROQUE SAENZ PEÑA');
insert into calles (nombre) values ('ROSA MOSQUETA');
insert into calles (nombre) values ('ROSARIO DE SANTA FE');
insert into calles (nombre) values ('ROSAS');
insert into calles (nombre) values ('RUBEN FERNANDEZ');
insert into calles (nombre) values ('RUBI');
insert into calles (nombre) values ('RUPU TROMEN (CAMINOS DE NUBES)');
insert into calles (nombre) values ('RUTA A ÑIRIHUAU');
insert into calles (nombre) values ('RUTA AEROPUERTO');
insert into calles (nombre) values ('RUTA NAC. 40 NORTE');
insert into calles (nombre) values ('RUTA NAC. 40 SUR');
insert into calles (nombre) values ('RUTA NAC.40 - CTE. LUIS PIEDRABUENA');
insert into calles (nombre) values ('RUTA NACIONAL 258');
insert into calles (nombre) values ('RUTA NACIONAL 77');
insert into calles (nombre) values ('RUTA NRO. 237');
insert into calles (nombre) values ('RUTA PROV. 77 (DESVIO A COLON.SUIZA HAST');
insert into calles (nombre) values ('RUTA PROV. 79 ( DESV.A COL. SUIZA');
insert into calles (nombre) values ('RUTA PROVINCIAL 82');
insert into calles (nombre) values ('SAGITARIO');
insert into calles (nombre) values ('SALTA');
insert into calles (nombre) values ('SALTA - MELIPAL');
insert into calles (nombre) values ('SALVADOR (DINA HUAPI)');
insert into calles (nombre) values ('SAN ANTONIO');
insert into calles (nombre) values ('SAN CAYETANO');
insert into calles (nombre) values ('SAN JOSE ( ENTRADA A TRANS.Y TTE.)');
insert into calles (nombre) values ('SAN JOSE DE COSTA RICA');
insert into calles (nombre) values ('SAN JUAN (MELIPAL)');
insert into calles (nombre) values ('SAN JUAN BOSCO');
insert into calles (nombre) values ('SAN LORENZO, BARILOCHE');
insert into calles (nombre) values ('SAN PABLO');
insert into calles (nombre) values ('SAN RAMON');
insert into calles (nombre) values ('SAN SALVADOR');
insert into calles (nombre) values ('SANTA ANA');
insert into calles (nombre) values ('SANTA CRUZ');
insert into calles (nombre) values ('SANTA ELISA');
insert into calles (nombre) values ('SANTA FE');
insert into calles (nombre) values ('SANTA ROSA');
insert into calles (nombre) values ('SANTIAGO ALBARRACIN');
insert into calles (nombre) values ('SANTIAGO DE CHILE');
insert into calles (nombre) values ('SARGENTO A. ROLANDO');
insert into calles (nombre) values ('SARGENTO RAMON ACOSTA');
insert into calles (nombre) values ('SARGENTO SERGIO GARCIA');
insert into calles (nombre) values ('SARMIENTO');
insert into calles (nombre) values ('SARMIENTO ESTE');
insert into calles (nombre) values ('SARMIENTO INFERIOR MELIPAL');
insert into calles (nombre) values ('SARMIENTO OESTE');
insert into calles (nombre) values ('SARMIENTO SUPERIOR MELIPAL');
insert into calles (nombre) values ('SAUCO');
insert into calles (nombre) values ('SAXON');
insert into calles (nombre) values ('SEGUNDA CORTADA');
insert into calles (nombre) values ('SEGUNDA DIAGONAL');
insert into calles (nombre) values ('SEGUNDO SOMBRA');
insert into calles (nombre) values ('SEIS ( CAHIU)');
insert into calles (nombre) values ('SELVA NEGRA');
insert into calles (nombre) values ('SGTO PRIMERO GUILLERMO OSES');
insert into calles (nombre) values ('SHAQUIL');
insert into calles (nombre) values ('SHOPPING LAS TERRAZAS-CO CATEDRAL');
insert into calles (nombre) values ('SIEMPREVIVA');
insert into calles (nombre) values ('SIERRA COLORADA');
insert into calles (nombre) values ('SIETE ( REGLE)');
insert into calles (nombre) values ('SIETE COLORES');
insert into calles (nombre) values ('SIN NOMBRE');
insert into calles (nombre) values ('SOBERANIA ARGENTINA');
insert into calles (nombre) values ('SOBREPUESTO');
insert into calles (nombre) values ('SOLDADO ARNALDO ZABALA');
insert into calles (nombre) values ('SOLDADO HORACIO GIRAUDO');
insert into calles (nombre) values ('SOLDADO JOSE ALLENDE');
insert into calles (nombre) values ('SOLDADO OLAVARRIA');
insert into calles (nombre) values ('SOLDADO RAMON CABRERA');
insert into calles (nombre) values ('SOLDADO RICARDO AUSTIN');
insert into calles (nombre) values ('SUBTENIENTE JUAN BALDINI');
insert into calles (nombre) values ('SUBTENIENTE OSCAR SILVA');
insert into calles (nombre) values ('SUCRE');
insert into calles (nombre) values ('SUIPACHA');
insert into calles (nombre) values ('SUIZA');
insert into calles (nombre) values ('SURUBI');
insert into calles (nombre) values ('TACHURI');
insert into calles (nombre) values ('TACUARI');
insert into calles (nombre) values ('TAIQUE');
insert into calles (nombre) values ('TAITAO (LUGAR DE RUIDO)');
insert into calles (nombre) values ('TANDIL');
insert into calles (nombre) values ('TARIJA');
insert into calles (nombre) values ('TEGUCIGALPA');
insert into calles (nombre) values ('TEHUELCHES');
insert into calles (nombre) values ('TENIENTE EMILIO ESPINOZA');
insert into calles (nombre) values ('TEPU');
insert into calles (nombre) values ('TIACA (EL FRUTILLAR)');
insert into calles (nombre) values ('TIERRA DEL FUEGO');
insert into calles (nombre) values ('TINEO');
insert into calles (nombre) values ('TIQUE');
insert into calles (nombre) values ('TOCUYO');
insert into calles (nombre) values ('TOPA TOPA');
insert into calles (nombre) values ('TORCAZAS');
insert into calles (nombre) values ('TORDOS');
insert into calles (nombre) values ('TORRE CAMPANILLE');
insert into calles (nombre) values ('TRAFUL');
insert into calles (nombre) values ('TRAIQUEN');
insert into calles (nombre) values ('TREBOL');
insert into calles (nombre) values ('TRECE -(MARI QUILA)');
insert into calles (nombre) values ('TRENCA (CALANDRIA)');
insert into calles (nombre) values ('TRES (QUILA)');
insert into calles (nombre) values ('TRES DE MAYO');
insert into calles (nombre) values ('TROCHITA PATAGONICA');
insert into calles (nombre) values ('TROMEN (NUBES)');
insert into calles (nombre) values ('TRONADOR');
insert into calles (nombre) values ('TRONADOR-MELIPAL');
insert into calles (nombre) values ('TROYA');
insert into calles (nombre) values ('TUCUMAN');
insert into calles (nombre) values ('TUNQUELEN (LUGAR DE PAZ)');
insert into calles (nombre) values ('TUPAC AMARU');
insert into calles (nombre) values ('TUPUNGATO');
insert into calles (nombre) values ('ULISES');
insert into calles (nombre) values ('UNIDAD LOS COIHUES');
insert into calles (nombre) values ('UNIDAD MELIPAL');
insert into calles (nombre) values ('UNIDAD NAHUEL MALAL');
insert into calles (nombre) values ('UNIDAD P-PINAR FESTA');
insert into calles (nombre) values ('UNIDAD PENINSULA');
insert into calles (nombre) values ('UNIDAD PINAR DEL LAG');
insert into calles (nombre) values ('UNIDAD POSTAL LOS COHIUES NRO');
insert into calles (nombre) values ('URBANIZACION DEL ESTE');
insert into calles (nombre) values ('USHUAIA');
insert into calles (nombre) values ('USHUAIA Bº 106 VIV.');
insert into calles (nombre) values ('VAL SERENO');
insert into calles (nombre) values ('VALAIS');
insert into calles (nombre) values ('VALCHETA');
insert into calles (nombre) values ('VALERIANA');
insert into calles (nombre) values ('VALLE DE LOS ÑIRES');
insert into calles (nombre) values ('VAPOR CONDOR');
insert into calles (nombre) values ('VEINTE DE FEBRERO');
insert into calles (nombre) values ('VEINTE DE JUNIO');
insert into calles (nombre) values ('VEINTICINCO DE MAYO');
insert into calles (nombre) values ('VEINTICUATRO DE SEPTIEMBRE');
insert into calles (nombre) values ('VENEZUELA (DINA HUAPI)');
insert into calles (nombre) values ('VENTISQUERO NEGRO');
insert into calles (nombre) values ('VICEALMIRANTE EDUARDO O`CONNOR');
insert into calles (nombre) values ('VICENTE FORTE');
insert into calles (nombre) values ('VICENTE ROBLES');
insert into calles (nombre) values ('VICTORIA');
insert into calles (nombre) values ('VICTORIA OCAMPO');
insert into calles (nombre) values ('VIEJA PISCICULTURA');
insert into calles (nombre) values ('VIEJOS POBLADORES');
insert into calles (nombre) values ('VILCAPUGIO');
insert into calles (nombre) values ('VILLA CATEDRAL');
insert into calles (nombre) values ('VILLA LOS COIHUES');
insert into calles (nombre) values ('VINCENT VAN GOGH');
insert into calles (nombre) values ('VUELTA DE OBLIGADO');
insert into calles (nombre) values ('WALDO BELLOSO');
insert into calles (nombre) values ('WALDO DE LOS RIOS');
insert into calles (nombre) values ('YAL NEGRO');
insert into calles (nombre) values ('YAPEYU (MELIPAL)');
insert into calles (nombre) values ('YARETA');
insert into calles (nombre) values ('YUNCO');
insert into calles (nombre) values ('ZORZALES');
insert into calles (nombre) values ('ZURICH');