INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('JUNIN',1),
	 ('MAR DEL PLATA',1),
	 ('SAN CARLOS DE BARILOCHE',1),
	 ('BUENOS AIRES',1),
	 ('ROSARIO',1),
	 ('SALTA',1),
	 ('CHILE',1),
	 ('CORRIENTES',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('CAPITAL FEDERAL',1),
	 ('VILLA TRAFUL',1),
	 ('EL BOLSON',1),
	 ('EL DORADO (MISIONES)',1),
	 ('MENDOZA',1),
	 ('CHIMPAY',1),
	 ('ESQUEL',1),
	 ('SAN MARTIN DE LOS ANDES',1),
	 ('LAGO PUELO',1),
	 ('LA PLATA',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('CORDOBA',1),
	 ('PARANA',1),
	 ('COMODORO RIVADAVIA',1),
	 ('VIEDMA',1),
	 ('BAHIA BLANCA',1),
	 ('LAS GRUTAS',1),
	 ('SANTA FE',1),
	 ('PUERTO MADRYN',1),
	 ('BRASIL',1),
	 ('VILLA REGINA',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('NEUQUEN',1),
	 ('POSADAS (MISIONES)',1),
	 ('TUCUMAN',1),
	 ('RAMOS MEJIA',1),
	 ('TRES ARROYOS',1),
	 ('TRELLEW',1),
	 ('COMALLO',1),
	 ('JACOBACCI',1),
	 ('CHACABUCO',1),
	 ('CHACO',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('ING. JACOBACCI',1),
	 ('SANTA CRUZ',1),
	 ('GENERAL ROCA',1),
	 ('SANTA ROSA (LA PAMPA)',1),
	 ('EL  VALLE',1),
	 ('URUGUAY',1),
	 ('RESISTENCIA',1),
	 ('VENADO TUERTO',1),
	 ('TRAFUL',1),
	 ('SAN JUAN',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('CIPOLETTI',1),
	 ('PARAGUAY',1),
	 ('LA PAMPA',1),
	 ('LA RIOJA',1),
	 ('JUJUY',1),
	 ('FORMOSA',1),
	 ('MISIONES',1),
	 ('SANTIAGO  DEL  ESTERO',1),
	 ('PUERTO  BELGRANO',1),
	 ('DESCONOCIDO',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('RAWSON',1),
	 ('CUTRAL CO',1),
	 ('LLANQUIN',1),
	 ('MARQUINCHAO',1),
	 ('CALETA OLIVIA',1),
	 ('CATAMARCA',1),
	 ('SAN LUIS',1),
	 ('CINCO SALTOS',1),
	 ('ROCA',1),
	 ('UNIVERSIDAD DE CORDOBA',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('PINAMAR',1),
	 ('LAMARQUE',1),
	 ('CHOELE CHOEL',1),
	 ('BELTRAN',1),
	 ('CERVANTES',1),
	 ('CHUBUT',1),
	 ('ZAPALA',1),
	 ('AUSTRALIA',1),
	 ('MADRIN',1),
	 ('EL HOYO',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('COPAHUE',1),
	 ('FUERA DE SERVICIO',1),
	 ('VILLA GESELL',1),
	 ('NECOCHEA',1),
	 ('ALLEN',1),
	 ('CENTENARIO',1),
	 ('RIO CUARTO',1),
	 ('CASILLA RODANTE',1),
	 ('PERITO MORENO',1),
	 ('LOS MENUCO',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('PILCANIYEU',1),
	 ('MENCUE',1),
	 ('CATARATAS DEL  IGUAZU',1),
	 ('RIO COLORADO',1),
	 ('PUNTA ARENA (CHILE)',1),
	 ('MENUCO',1),
	 ('AEROPUERTO',1),
	 ('CIRCUITO CHICO',1),
	 ('IGUAZU',1),
	 ('GUALEGUAY',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('RIO GRANDE',1),
	 ('TIERRA DEL FUEGO',1),
	 ('PIEDRA DEL AGUILA',1),
	 ('MASCARDI',1),
	 ('MOTORHOME',1),
	 ('CONFLUENCIA',1),
	 ('SAN NICOLAS',1),
	 ('PUENTE DEL RIO LIMAY',1),
	 ('CHAPADMALAL',1),
	 ('SIERRAS COLORADAS',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('TRENQUE LAUQUEN',1),
	 ('C V S',1),
	 ('BALLESTERO',1),
	 ('BOMBAI',1),
	 ('CALAFATE',1),
	 ('ARROYITO',1),
	 ('CUZCO PERU',1),
	 ('CERRO CATEDRAL',1),
	 ('CRUCE CAMINERO',1),
	 ('EL CHOCON',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('CHOCON',1),
	 ('RIO LIMAY',1),
	 ('MASTER BUS',1),
	 ('CATRIEL',1),
	 ('SANTA TERESITA',1),
	 ('VILLA DEL ROSARIO',1),
	 ('ARROYO CABRAL',1),
	 ('CAÑADA DE GOMEZ',1),
	 ('LAGUNA LARGA',1),
	 ('CONCORDIA',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('USHUAIA',1),
	 ('LIMAY',1),
	 ('ENTRE RIOS',1),
	 ('GENERAL PICO',1),
	 ('CAMBORIU',1),
	 ('RIOS GALLEGOS',1),
	 ('PUERTO IGUAZU',1),
	 ('CORONEL DORREGO',1),
	 ('MARCOS LAURI',1),
	 ('EL CUY',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('BUENOS AIRES LA PLATA',1),
	 ('GENERAL ACHA',1),
	 ('CLORINDA',1),
	 ('AEROPUERTO ESQUEL ',1),
	 ('PEUAJO',1),
	 ('AEROPUERTO NQN',1),
	 ('TRANSTUR',1),
	 ('AVELLANEDA PROV, BS.AS.',1),
	 ('PUERTO MONTT  ',1),
	 ('VALDIVIA',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('GONZA TOUR',1),
	 ('RADA TILLY',1),
	 ('LLAO LLAO',1),
	 ('TANDIL',1),
	 ('PERGAMINO PROV. BS. AS.',1),
	 ('SALIQUELO',1),
	 ('GAIMAN',1),
	 ('MAR DE AJO',1),
	 ('RAFAELA PCIA SANTA FE',1),
	 ('SAN ANTONIO DE ARECO',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('LUIS BELTRAN',1),
	 ('CONESA',1),
	 ('DINA HUAPI',1),
	 ('CHAJARI',1),
	 ('GONZALEZ CATAN ',1),
	 ('RAMALLOS PCIA ,BS AS, ',1),
	 ('ANILLACO',1),
	 ('MONTEVIDEO URUGUAY',1),
	 ('GODOY',1),
	 ('OLABARRIA PCIA DE BS, AS.',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('MAQUINCHAO',1),
	 ('EL MANSO',1),
	 ('MANSO',1),
	 ('ARRECIFES ',1),
	 ('CHIVILCOY',1),
	 ('GENERAL ALVEAR',1),
	 ('PIGUE',1),
	 ('SENILLOSA',1),
	 ('SANTIAGO DE CHILE',1),
	 ('MIRAMAR',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('BRAGADO',1),
	 ('CAMPANA PCI DE BS. AS.',1),
	 ('GOYA',1),
	 ('REGINA',1),
	 ('ING. HUERGO',1),
	 ('PEHUAJO PCIA . BS, AS.',1),
	 ('CHINCHINALES',1),
	 ('COLON PCIA BS ,AS.',1),
	 ('ADUANA ARGENTINA',1),
	 ('CAÑUELAS',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('BUSES ILOMAR',1),
	 ('FLORENCIO VARELA',1),
	 ('LAVALLOL',1),
	 ('TEMUCO',1),
	 ('LUCERO',1),
	 ('TARTAGAL',1),
	 ('VILLA MANZANO',1),
	 ('RINCON DE LOS SAUCES',1),
	 ('BOLIVIA',1),
	 ('RAFTING',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('PUCON',1),
	 ('BURZACO PROV, BS, AS',1),
	 ('LUJAN PROV. BS,AS,',1),
	 ('PLOTIER',1),
	 ('CERRO VALLO',1),
	 ('QUILMES ',1),
	 ('AEROPUERTO - EL BOLSON',1),
	 ('PAEZ',1),
	 ('PRINCESA  DEL NORTE',1),
	 ('AEROPUERTO - VILLA LA ANGOSTURA',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('RIO NEGRO  BELISLE',1),
	 ('TALCA ',1),
	 ('BLANTOUR',1),
	 ('BOLICHE CEREBRO',1),
	 ('ESTADIO MUNICIPAL ',1),
	 ('HOTEL',1),
	 ('CANCHAS ADEFUL',1),
	 ('CLUB ESTUDIANTES UNIDOS',1),
	 ('TERMINAL',1),
	 ('EXCURCION',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('PUNTA ALTA',1),
	 ('RGA SANTA ROSA TURISMO',1),
	 ('ALDEA RUTA 23',1),
	 ('LOS CEREZOS',1),
	 ('VALCHETA',1),
	 ('TANGO INN 12 DE OCT--1939',1),
	 ('DON ORIONE KM1505',1),
	 ('VILLA MARIA',1),
	 ('INVAP',1),
	 ('CAMPANARIO KM 16200 BUSTILLO',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('CENTRO CIVICO',1),
	 ('EPUYEN',1),
	 ('VALLE DEL SOL KM 23',1),
	 ('RANCHO W',1),
	 ('DISCO GRISU',1),
	 ('BOWLING ',1),
	 ('CARLOS PAZ',1),
	 ('CERRO CAMPANARIO',1),
	 ('TERMAS',1),
	 ('ALEMANIA 275 GIMNACIO',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('CANCHA PUERTO MORENO',1),
	 ('MONTE CLARO',1),
	 ('CLUB PEHUENES ',1),
	 ('GIMNASIO N1',1),
	 ('GIMNASIO 3',1),
	 ('DO SANTOS ',1),
	 ('CERRO OTTO',1),
	 ('QUINCHO BESCHTED Y DOS DE AGOSTO    COPELO     ',1),
	 ('CANCHA CRUZ DEL SUR',1),
	 ('TOM WESLEY',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('CLUB NEWENCHE',1),
	 ('CIRCULO CHILENO',1),
	 ('BYPASS',1),
	 ('CERRO BALLO',1),
	 ('INSTITUTO BALSEIRO',1),
	 ('SHOPPING',1),
	 ('COLONIA SUIZA',1),
	 ('POMONA',1),
	 ('PUERTO PAÑUELO',1),
	 ('DORREGO',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('CASTELLI PCIA BS AS',1),
	 ('ESTANCIA SAN RAMON',1),
	 ('ESTADIO ESTUDIANTES BARILOCHE',1),
	 ('CANOPY',1),
	 ('CERRO VIEJO',1),
	 ('BASSIA',1),
	 ('LOS VAQUEANOS',1),
	 ('LAGO GUTIERREZ',1),
	 ('TAMBO VIEJO',1),
	 ('PISTA HIELO',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('MONTAIN',1),
	 ('CABRERA BUSES',1),
	 ('ECO SKY',1),
	 ('LOS ANTIGUOS',1),
	 ('KAYAK',1),
	 ('PARQUE INDUSTRIAL',1),
	 ('MAÑIO',1),
	 ('PLAZA UNO',1),
	 ('ESCAPE ROOM',1),
	 ('MAINQUE',1);
INSERT INTO sgpc.lugares (nombre,activo) VALUES
	 ('GRISU',1),
	 ('GENUX',1),
	 ('ROCKETS',1),
	 ('PUNTA ALTA',1),
	 ('PILETAS',1),
	 ('PUERTO MORENO 10',1),
	 ('CERVECERIA PATAGONIA',1),
	 ('BOLICHE',1),
	 ('CAMINERA',1);
