insert into lugares (nombre) values ('ADUANA ARGENTINA');
insert into lugares (nombre) values ('AEROPUERTO');
insert into lugares (nombre) values ('AEROPUERTO - EL BOLSON');
insert into lugares (nombre) values ('AEROPUERTO - VILLA LA ANGOSTURA');
insert into lugares (nombre) values ('AEROPUERTO ESQUEL');
insert into lugares (nombre) values ('AEROPUERTO NQN');
insert into lugares (nombre) values ('ALDEA RUTA 23');
insert into lugares (nombre) values ('ALEMANIA 275 GIMNACIO');
insert into lugares (nombre) values ('ALLEN');
insert into lugares (nombre) values ('ANILLACO');
insert into lugares (nombre) values ('ARRECIFES');
insert into lugares (nombre) values ('ARROYITO');
insert into lugares (nombre) values ('ARROYO CABRAL');
insert into lugares (nombre) values ('AUSTRALIA');
insert into lugares (nombre) values ('AVELLANEDA PROV, BS.AS.');
insert into lugares (nombre) values ('BAHIA BLANCA');
insert into lugares (nombre) values ('BALLESTERO');
insert into lugares (nombre) values ('BASSIA');
insert into lugares (nombre) values ('BELTRAN');
insert into lugares (nombre) values ('BLANTOUR');
insert into lugares (nombre) values ('BOLICHE');
insert into lugares (nombre) values ('BOLICHE CEREBRO');
insert into lugares (nombre) values ('BOLIVIA');
insert into lugares (nombre) values ('BOMBAI');
insert into lugares (nombre) values ('BOWLING');
insert into lugares (nombre) values ('BRAGADO');
insert into lugares (nombre) values ('BRASIL');
insert into lugares (nombre) values ('BUENOS AIRES');
insert into lugares (nombre) values ('BUENOS AIRES LA PLATA');
insert into lugares (nombre) values ('BURZACO PROV, BS, AS');
insert into lugares (nombre) values ('BUSES ILOMAR');
insert into lugares (nombre) values ('BYPASS');
insert into lugares (nombre) values ('C V S');
insert into lugares (nombre) values ('CABRERA BUSES');
insert into lugares (nombre) values ('CALAFATE');
insert into lugares (nombre) values ('CALETA OLIVIA');
insert into lugares (nombre) values ('CAMBORIU');
insert into lugares (nombre) values ('CAMINERA');
insert into lugares (nombre) values ('CAMPANA PCI DE BS. AS.');
insert into lugares (nombre) values ('CAMPANARIO KM 16200 BUSTILLO');
insert into lugares (nombre) values ('CANCHA CRUZ DEL SUR');
insert into lugares (nombre) values ('CANCHA PUERTO MORENO');
insert into lugares (nombre) values ('CANCHAS ADEFUL');
insert into lugares (nombre) values ('CANOPY');
insert into lugares (nombre) values ('CAÑADA DE GOMEZ');
insert into lugares (nombre) values ('CAÑUELAS');
insert into lugares (nombre) values ('CAPITAL FEDERAL');
insert into lugares (nombre) values ('CARLOS PAZ');
insert into lugares (nombre) values ('CASILLA RODANTE');
insert into lugares (nombre) values ('CASTELLI PCIA BS AS');
insert into lugares (nombre) values ('CATAMARCA');
insert into lugares (nombre) values ('CATARATAS DEL  IGUAZU');
insert into lugares (nombre) values ('CATRIEL');
insert into lugares (nombre) values ('CENTENARIO');
insert into lugares (nombre) values ('CENTRO CIVICO');
insert into lugares (nombre) values ('CERRO BALLO');
insert into lugares (nombre) values ('CERRO CAMPANARIO');
insert into lugares (nombre) values ('CERRO CATEDRAL');
insert into lugares (nombre) values ('CERRO OTTO');
insert into lugares (nombre) values ('CERRO VALLO');
insert into lugares (nombre) values ('CERRO VIEJO');
insert into lugares (nombre) values ('CERVANTES');
insert into lugares (nombre) values ('CERVECERIA PATAGONIA');
insert into lugares (nombre) values ('CHACABUCO');
insert into lugares (nombre) values ('CHACO');
insert into lugares (nombre) values ('CHAJARI');
insert into lugares (nombre) values ('CHAPADMALAL');
insert into lugares (nombre) values ('CHILE');
insert into lugares (nombre) values ('CHIMPAY');
insert into lugares (nombre) values ('CHINCHINALES');
insert into lugares (nombre) values ('CHIVILCOY');
insert into lugares (nombre) values ('CHOCON');
insert into lugares (nombre) values ('CHOELE CHOEL');
insert into lugares (nombre) values ('CHUBUT');
insert into lugares (nombre) values ('CINCO SALTOS');
insert into lugares (nombre) values ('CIPOLETTI');
insert into lugares (nombre) values ('CIRCUITO CHICO');
insert into lugares (nombre) values ('CIRCULO CHILENO');
insert into lugares (nombre) values ('CLORINDA');
insert into lugares (nombre) values ('CLUB ESTUDIANTES UNIDOS');
insert into lugares (nombre) values ('CLUB NEWENCHE');
insert into lugares (nombre) values ('CLUB PEHUENES');
insert into lugares (nombre) values ('COLON PCIA BS ,AS.');
insert into lugares (nombre) values ('COLONIA SUIZA');
insert into lugares (nombre) values ('COMALLO');
insert into lugares (nombre) values ('COMODORO RIVADAVIA');
insert into lugares (nombre) values ('CONCORDIA');
insert into lugares (nombre) values ('CONESA');
insert into lugares (nombre) values ('CONFLUENCIA');
insert into lugares (nombre) values ('COPAHUE');
insert into lugares (nombre) values ('CORDOBA');
insert into lugares (nombre) values ('CORONEL DORREGO');
insert into lugares (nombre) values ('CORRIENTES');
insert into lugares (nombre) values ('CRUCE CAMINERO');
insert into lugares (nombre) values ('CUTRAL CO');
insert into lugares (nombre) values ('CUZCO PERU');
insert into lugares (nombre) values ('DESCONOCIDO');
insert into lugares (nombre) values ('DINA HUAPI');
insert into lugares (nombre) values ('DISCO GRISU');
insert into lugares (nombre) values ('DO SANTOS');
insert into lugares (nombre) values ('DON ORIONE KM1505');
insert into lugares (nombre) values ('DORREGO');
insert into lugares (nombre) values ('ECO SKY');
insert into lugares (nombre) values ('EL  VALLE');
insert into lugares (nombre) values ('EL BOLSON');
insert into lugares (nombre) values ('EL CHOCON');
insert into lugares (nombre) values ('EL CUY');
insert into lugares (nombre) values ('EL DORADO (MISIONES)');
insert into lugares (nombre) values ('EL HOYO');
insert into lugares (nombre) values ('EL MANSO');
insert into lugares (nombre) values ('ENTRE RIOS');
insert into lugares (nombre) values ('EPUYEN');
insert into lugares (nombre) values ('ESCAPE ROOM');
insert into lugares (nombre) values ('ESQUEL');
insert into lugares (nombre) values ('ESTADIO ESTUDIANTES BARILOCHE');
insert into lugares (nombre) values ('ESTADIO MUNICIPAL');
insert into lugares (nombre) values ('ESTANCIA SAN RAMON');
insert into lugares (nombre) values ('EXCURCION');
insert into lugares (nombre) values ('FLORENCIO VARELA');
insert into lugares (nombre) values ('FORMOSA');
insert into lugares (nombre) values ('FUERA DE SERVICIO');
insert into lugares (nombre) values ('GAIMAN');
insert into lugares (nombre) values ('GENERAL ACHA');
insert into lugares (nombre) values ('GENERAL ALVEAR');
insert into lugares (nombre) values ('GENERAL PICO');
insert into lugares (nombre) values ('GENERAL ROCA');
insert into lugares (nombre) values ('GENUX');
insert into lugares (nombre) values ('GIMNASIO 3');
insert into lugares (nombre) values ('GIMNASIO N1');
insert into lugares (nombre) values ('GODOY');
insert into lugares (nombre) values ('GONZA TOUR');
insert into lugares (nombre) values ('GONZALEZ CATAN');
insert into lugares (nombre) values ('GOYA');
insert into lugares (nombre) values ('GRISU');
insert into lugares (nombre) values ('GUALEGUAY');
insert into lugares (nombre) values ('HOTEL');
insert into lugares (nombre) values ('IGUAZU');
insert into lugares (nombre) values ('ING. HUERGO');
insert into lugares (nombre) values ('ING. JACOBACCI');
insert into lugares (nombre) values ('INSTITUTO BALSEIRO');
insert into lugares (nombre) values ('INVAP');
insert into lugares (nombre) values ('JACOBACCI');
insert into lugares (nombre) values ('JUJUY');
insert into lugares (nombre) values ('JUNIN');
insert into lugares (nombre) values ('KAYAK');
insert into lugares (nombre) values ('LA PAMPA');
insert into lugares (nombre) values ('LA PLATA');
insert into lugares (nombre) values ('LA RIOJA');
insert into lugares (nombre) values ('LAGO GUTIERREZ');
insert into lugares (nombre) values ('LAGO PUELO');
insert into lugares (nombre) values ('LAGUNA LARGA');
insert into lugares (nombre) values ('LAMARQUE');
insert into lugares (nombre) values ('LAS GRUTAS');
insert into lugares (nombre) values ('LAVALLOL');
insert into lugares (nombre) values ('LIMAY');
insert into lugares (nombre) values ('LLANQUIN');
insert into lugares (nombre) values ('LLAO LLAO');
insert into lugares (nombre) values ('LOS ANTIGUOS');
insert into lugares (nombre) values ('LOS CEREZOS');
insert into lugares (nombre) values ('LOS MENUCO');
insert into lugares (nombre) values ('LOS VAQUEANOS');
insert into lugares (nombre) values ('LUCERO');
insert into lugares (nombre) values ('LUIS BELTRAN');
insert into lugares (nombre) values ('LUJAN PROV. BS,AS,');
insert into lugares (nombre) values ('MADRIN');
insert into lugares (nombre) values ('MAINQUE');
insert into lugares (nombre) values ('MANSO');
insert into lugares (nombre) values ('MAÑIO');
insert into lugares (nombre) values ('MAQUINCHAO');
insert into lugares (nombre) values ('MAR DE AJO');
insert into lugares (nombre) values ('MAR DEL PLATA');
insert into lugares (nombre) values ('MARCOS LAURI');
insert into lugares (nombre) values ('MARQUINCHAO');
insert into lugares (nombre) values ('MASCARDI');
insert into lugares (nombre) values ('MASTER BUS');
insert into lugares (nombre) values ('MENCUE');
insert into lugares (nombre) values ('MENDOZA');
insert into lugares (nombre) values ('MENUCO');
insert into lugares (nombre) values ('MIRAMAR');
insert into lugares (nombre) values ('MISIONES');
insert into lugares (nombre) values ('MONTAIN');
insert into lugares (nombre) values ('MONTE CLARO');
insert into lugares (nombre) values ('MONTEVIDEO URUGUAY');
insert into lugares (nombre) values ('MOTORHOME');
insert into lugares (nombre) values ('NECOCHEA');
insert into lugares (nombre) values ('NEUQUEN');
insert into lugares (nombre) values ('OLABARRIA PCIA DE BS, AS.');
insert into lugares (nombre) values ('PAEZ');
insert into lugares (nombre) values ('PARAGUAY');
insert into lugares (nombre) values ('PARANA');
insert into lugares (nombre) values ('PARQUE INDUSTRIAL');
insert into lugares (nombre) values ('PEHUAJO PCIA . BS, AS.');
insert into lugares (nombre) values ('PERGAMINO PROV. BS. AS.');
insert into lugares (nombre) values ('PERITO MORENO');
insert into lugares (nombre) values ('PEUAJO');
insert into lugares (nombre) values ('PIEDRA DEL AGUILA');
insert into lugares (nombre) values ('PIGUE');
insert into lugares (nombre) values ('PILCANIYEU');
insert into lugares (nombre) values ('PILETAS');
insert into lugares (nombre) values ('PINAMAR');
insert into lugares (nombre) values ('PISTA HIELO');
insert into lugares (nombre) values ('PLAZA UNO');
insert into lugares (nombre) values ('PLOTIER');
insert into lugares (nombre) values ('POMONA');
insert into lugares (nombre) values ('POSADAS (MISIONES)');
insert into lugares (nombre) values ('PRINCESA  DEL NORTE');
insert into lugares (nombre) values ('PUCON');
insert into lugares (nombre) values ('PUENTE DEL RIO LIMAY');
insert into lugares (nombre) values ('PUERTO  BELGRANO');
insert into lugares (nombre) values ('PUERTO IGUAZU');
insert into lugares (nombre) values ('PUERTO MADRYN');
insert into lugares (nombre) values ('PUERTO MONTT');
insert into lugares (nombre) values ('PUERTO MORENO 10');
insert into lugares (nombre) values ('PUERTO PAÑUELO');
insert into lugares (nombre) values ('PUNTA ALTA');
insert into lugares (nombre) values ('PUNTA ALTA');
insert into lugares (nombre) values ('PUNTA ARENA (CHILE)');
insert into lugares (nombre) values ('QUILMES');
insert into lugares (nombre) values ('QUINCHO BESCHTED Y DOS DE AGOSTO    COPELO');
insert into lugares (nombre) values ('RADA TILLY');
insert into lugares (nombre) values ('RAFAELA PCIA SANTA FE');
insert into lugares (nombre) values ('RAFTING');
insert into lugares (nombre) values ('RAMALLOS PCIA ,BS AS,');
insert into lugares (nombre) values ('RAMOS MEJIA');
insert into lugares (nombre) values ('RANCHO W');
insert into lugares (nombre) values ('RAWSON');
insert into lugares (nombre) values ('REGINA');
insert into lugares (nombre) values ('RESISTENCIA');
insert into lugares (nombre) values ('RGA SANTA ROSA TURISMO');
insert into lugares (nombre) values ('RINCON DE LOS SAUCES');
insert into lugares (nombre) values ('RIO COLORADO');
insert into lugares (nombre) values ('RIO CUARTO');
insert into lugares (nombre) values ('RIO GRANDE');
insert into lugares (nombre) values ('RIO LIMAY');
insert into lugares (nombre) values ('RIO NEGRO  BELISLE');
insert into lugares (nombre) values ('RIOS GALLEGOS');
insert into lugares (nombre) values ('ROCA');
insert into lugares (nombre) values ('ROCKETS');
insert into lugares (nombre) values ('ROSARIO');
insert into lugares (nombre) values ('SALIQUELO');
insert into lugares (nombre) values ('SALTA');
insert into lugares (nombre) values ('SAN ANTONIO DE ARECO');
insert into lugares (nombre) values ('SAN CARLOS DE BARILOCHE');
insert into lugares (nombre) values ('SAN JUAN');
insert into lugares (nombre) values ('SAN LUIS');
insert into lugares (nombre) values ('SAN MARTIN DE LOS ANDES');
insert into lugares (nombre) values ('SAN NICOLAS');
insert into lugares (nombre) values ('SANTA CRUZ');
insert into lugares (nombre) values ('SANTA FE');
insert into lugares (nombre) values ('SANTA ROSA (LA PAMPA)');
insert into lugares (nombre) values ('SANTA TERESITA');
insert into lugares (nombre) values ('SANTIAGO  DEL  ESTERO');
insert into lugares (nombre) values ('SANTIAGO DE CHILE');
insert into lugares (nombre) values ('SENILLOSA');
insert into lugares (nombre) values ('SHOPPING');
insert into lugares (nombre) values ('SIERRAS COLORADAS');
insert into lugares (nombre) values ('TALCA');
insert into lugares (nombre) values ('TAMBO VIEJO');
insert into lugares (nombre) values ('TANDIL');
insert into lugares (nombre) values ('TANGO INN 12 DE OCT--1939');
insert into lugares (nombre) values ('TARTAGAL');
insert into lugares (nombre) values ('TEMUCO');
insert into lugares (nombre) values ('TERMAS');
insert into lugares (nombre) values ('TERMINAL');
insert into lugares (nombre) values ('TIERRA DEL FUEGO');
insert into lugares (nombre) values ('TOM WESLEY');
insert into lugares (nombre) values ('TRAFUL');
insert into lugares (nombre) values ('TRANSTUR');
insert into lugares (nombre) values ('TRELLEW');
insert into lugares (nombre) values ('TRENQUE LAUQUEN');
insert into lugares (nombre) values ('TRES ARROYOS');
insert into lugares (nombre) values ('TUCUMAN');
insert into lugares (nombre) values ('UNIVERSIDAD DE CORDOBA');
insert into lugares (nombre) values ('URUGUAY');
insert into lugares (nombre) values ('USHUAIA');
insert into lugares (nombre) values ('VALCHETA');
insert into lugares (nombre) values ('VALDIVIA');
insert into lugares (nombre) values ('VALLE DEL SOL KM 23');
insert into lugares (nombre) values ('VENADO TUERTO');
insert into lugares (nombre) values ('VIEDMA');
insert into lugares (nombre) values ('VILLA DEL ROSARIO');
insert into lugares (nombre) values ('VILLA GESELL');
insert into lugares (nombre) values ('VILLA MANZANO');
insert into lugares (nombre) values ('VILLA MARIA');
insert into lugares (nombre) values ('VILLA REGINA');
insert into lugares (nombre) values ('VILLA TRAFUL');
insert into lugares (nombre) values ('ZAPALA');