INSERT INTO nacionalidades (nacionalidad) VALUES ('Argentina');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Brasil');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Chile');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Afganistán');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Albania');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Alemania');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Andorra');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Angola');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Antigua y Barbuda');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Arabia Saudita');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Argelia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Armenia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Australia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Austria');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Bahamas');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Baréin');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Bangladés');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Barbados');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Bélgica');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Belice');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Benín');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Bielorrusia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Birmania');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Bolivia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Bosnia y Herzegovina');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Botsuana');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Bulgaria');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Burkina Faso');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Burundi');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Cabo Verde');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Camboya');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Camerún');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Canadá');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Catar');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Chad');
INSERT INTO nacionalidades (nacionalidad) VALUES ('China');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Chipre');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Colombia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Comoras');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Congo');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Costa Rica');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Croacia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Cuba');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Dinamarca');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Dominica');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Ecuador');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Egipto');
INSERT INTO nacionalidades (nacionalidad) VALUES ('El Salvador');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Emiratos Árabes Unidos');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Eslovaquia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Eslovenia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('España');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Estados Unidos');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Estonia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Etiopía');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Filipinas');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Finlandia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Francia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Gabón');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Gambia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Georgia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Ghana');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Granada');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Grecia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Guatemala');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Guinea');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Guinea-Bisáu');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Guinea Ecuatorial');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Guyana');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Haití');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Honduras');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Hungría');
INSERT INTO nacionalidades (nacionalidad) VALUES ('India');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Indonesia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Irak');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Irán');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Irlanda');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Islandia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Israel');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Italia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Jamaica');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Japón');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Jordania');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Kazajistán');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Kenia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Kirguistán');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Kiribati');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Kuwait');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Laos');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Letonia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Líbano');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Liberia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Libia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Liechtenstein');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Lituania');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Luxemburgo');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Macedonia del Norte');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Madagascar');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Malasia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Malaui');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Maldivas');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Malí');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Malta');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Marruecos');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Mauricio');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Mauritania');
INSERT INTO nacionalidades (nacionalidad) VALUES ('México');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Micronesia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Moldavia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Mónaco');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Mongolia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Montenegro');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Mozambique');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Namibia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Nauru');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Nepal');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Nicaragua');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Níger');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Nigeria');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Noruega');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Nueva Zelanda');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Omán');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Pakistán');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Palaos');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Palestina');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Panamá');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Papúa Nueva Guinea');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Paraguay');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Perú');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Polonia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Portugal');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Reino Unido');
INSERT INTO nacionalidades (nacionalidad) VALUES ('República Centroafricana');
INSERT INTO nacionalidades (nacionalidad) VALUES ('República Checa');
INSERT INTO nacionalidades (nacionalidad) VALUES ('República del Congo');
INSERT INTO nacionalidades (nacionalidad) VALUES ('República Democrática del Congo');
INSERT INTO nacionalidades (nacionalidad) VALUES ('República Dominicana');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Ruanda');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Rumanía');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Rusia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('San Cristóbal y Nieves');
INSERT INTO nacionalidades (nacionalidad) VALUES ('San Marino');
INSERT INTO nacionalidades (nacionalidad) VALUES ('San Vicente y las Granadinas');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Santa Lucía');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Santo Tomé y Príncipe');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Senegal');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Serbia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Seychelles');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Sierra Leona');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Singapur');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Siria');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Somalia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Sri Lanka');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Sudáfrica');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Sudán');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Sudán del Sur');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Suecia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Suiza');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Surinam');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Tailandia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Tanzania');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Tayikistán');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Timor Oriental');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Togo');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Tonga');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Trinidad y Tobago');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Túnez');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Turkmenistán');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Turquía');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Tuvalu');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Ucrania');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Uganda');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Uruguay');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Uzbekistán');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Vanuatu');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Vaticano');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Venezuela');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Vietnam');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Yemen');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Yibuti');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Zambia');
INSERT INTO nacionalidades (nacionalidad) VALUES ('Zimbabue');
